namespace Purview.ValueObjects.Serialization;

/// <summary>
/// A Guid-backed scalar value object that opts into Entity Framework Core key value generation, so an
/// unset key receives a time-ordered identifier.
/// </summary>
[Scalar(GenerateEFValueGenerator = true)]
public readonly partial record struct EFSequentialId
{
	/// <summary>Gets the serialized identifier value.</summary>
	public Guid Value { get; }

	static partial void OnValidate(Guid value)
	{
		if (value == Guid.Empty)
			throw new ArgumentException("Identifier cannot be empty.", nameof(value));
	}
}

/// <summary>An entity whose key is generated by the value-object key value generator.</summary>
sealed class EFAutoKeyEntity
{
	public EFSequentialId Id { get; set; }
}

/// <summary>
/// An entity that owns its identifiers: an explicit <c>ValueGeneratedNever()</c> must win over the
/// generated convention, which runs at the lowest configuration source.
/// </summary>
sealed class EFClientOwnedKeyEntity
{
	public EFSequentialId Id { get; set; }
}
