<Project>
	<PropertyGroup>
		<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
		<RoslynVersion>5.9.0</RoslynVersion>
		<TUnitVersion>1.67.0</TUnitVersion>
		<PurviewSGFVersion>1.0.0-prerelease.42</PurviewSGFVersion>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="Purview.SourceGeneratorFramework" Version="$(PurviewSGFVersion)" />
		<PackageVersion Include="Purview.SourceGeneratorFramework.Testing.TUnit" Version="$(PurviewSGFVersion)" />
		<PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
		<PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="$(RoslynVersion)" />
		<PackageVersion Include="Microsoft.CodeAnalysis.Common" Version="$(RoslynVersion)" />
		<PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="$(RoslynVersion)" />
		<PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="$(RoslynVersion)" />
	</ItemGroup>
	<ItemGroup Label="Testing">
		<PackageVersion Include="TUnit" Version="$(TUnitVersion)" />
		<PackageVersion Include="TUnit.Mocks" Version="$(TUnitVersion)" />
		<PackageVersion Include="Bogus" Version="35.6.5" />
	</ItemGroup>
</Project>
