using Microsoft.EntityFrameworkCore;
using Purview.ValueObjects.Serialization;

namespace Purview.ValueObjects.EFCompatibility;

/// <summary>
/// A scalar value object whose key value is generated by Entity Framework Core, so this type also proves
/// the generated key value generator, the identifier helper, and the key generator convention work on every
/// supported Entity Framework Core version.
/// </summary>
[Scalar(GenerateEFValueGenerator = true)]
public readonly partial record struct CompatibilityId
{
	/// <summary>Gets the identifier value.</summary>
	public Guid Value { get; }

	static partial void OnValidate(Guid value)
	{
		if (value == Guid.Empty)
			throw new ArgumentException("Identifier cannot be empty.", nameof(value));
	}
}

/// <summary>A scalar value object persisted in its own column through a generated value converter.</summary>
[Scalar]
public readonly partial record struct CompatibilityCode
{
	/// <summary>Gets the code value.</summary>
	public string Value { get; }

	static partial void OnValidate(string value)
	{
		if (string.IsNullOrWhiteSpace(value))
			throw new ArgumentException("Code cannot be empty.", nameof(value));
	}
}

/// <summary>
/// A complex value object mapped to a JSON column. This mapping is a value converter, so it works on every
/// Entity Framework Core version the package supports.
/// </summary>
[ValueObject(EFMapping = EntityFrameworkMapping.Json)]
public readonly partial record struct CompatibilityStamp
{
	/// <summary>Gets the recorded time.</summary>
	public DateTimeOffset RecordedAt { get; }

	/// <summary>Gets the origin of the stamp.</summary>
	public string Origin { get; }
}

/// <summary>
/// A complex value object mapped as an Entity Framework Core complex type, which needs EF Core 8 or later.
/// Against EF Core 7 the generator reports VO1019 and leaves the mapping out.
/// </summary>
[ValueObject]
public readonly partial record struct CompatibilityMoney
{
	/// <summary>Gets the amount.</summary>
	public decimal Amount { get; }

	/// <summary>Gets the currency of the amount.</summary>
	public CompatibilityCode Currency { get; }
}

/// <summary>
/// An entity that uses every value object mapping this project declares, so one model exercises the
/// converters, the JSON column, and - from EF Core 8 - the complex type.
/// </summary>
sealed class CompatibilityEntity
{
	/// <summary>Gets or sets the generated key.</summary>
	public CompatibilityId Id { get; set; }

	/// <summary>Gets or sets the code column.</summary>
	public CompatibilityCode Code { get; set; }

	/// <summary>Gets or sets the JSON column.</summary>
	public CompatibilityStamp Stamp { get; set; }

#if !NET8_0
	/// <summary>Gets or sets the complex type mapped to columns, which needs EF Core 8 or later.</summary>
	public CompatibilityMoney Total { get; set; }
#endif
}

/// <summary>
/// The context under test. It maps the value objects through the generated registry and registers the
/// generated key value generator convention, exactly as an application would.
/// </summary>
sealed class CompatibilityDbContext(DbContextOptions<CompatibilityDbContext> options) : DbContext(options)
{
	/// <summary>Gets the entity set.</summary>
	public DbSet<CompatibilityEntity> Entities => Set<CompatibilityEntity>();

	protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
	{
		base.ConfigureConventions(configurationBuilder);

		configurationBuilder.UseValueObjectKeyGenerators();
	}

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.ConfigureValueObjects();
	}
}
