namespace Purview.ValueObjects.SourceGenerator.ValueObject;

static partial class ComplexValueObjectEmitter
{
	public static void Emit(CodeWriter writer, ComplexValueObjectModel model)
	{
		writer.AutoGeneratedHeader();

		if (model.TypeModel.Namespace is not null)
			writer.FileScopedNamespace(model.TypeModel.Namespace);

		TypeDeclarationOptions declaration = new(model.TypeModel.Name, model.Accessibility)
		{
			Kind = GetTypeKind(model),
			IsPartial = true,
			IsSealed = false,
			IsReadOnly = model.IsReadOnly,
			Attributes = BuildTypeAttributes(model),
			Interfaces = BuildInterfaces(model),
		};

		writer.Type(declaration, body => EmitBody(body, model));
	}

	static void EmitBody(CodeWriter writer, ComplexValueObjectModel model)
	{
		EmitOnNormalizeDeclaration(writer, model);
		EmitCreateFactory(writer, model);
		EmitOnValidateDeclaration(writer, model);
		EmitHydrateFactory(writer, model);
		EmitEmpty(writer, model);
		EmitConstructor(writer, model);
		EmitEfConstructor(writer, model);
		EmitEquality(writer, model);
		EmitOperators(writer, model);
		EmitComparison(writer, model);
		EmitJsonConverter(writer, model);
	}

	static TypeDeclarationKind GetTypeKind(ComplexValueObjectModel model)
	{
		return model.IsRecord
			? model.IsReferenceType
				? TypeDeclarationKind.RecordClass
				: TypeDeclarationKind.RecordStruct
			: model.IsReferenceType
				? TypeDeclarationKind.Class
				: TypeDeclarationKind.Struct;
	}

	internal static TypeReference ValueObjectType(ComplexValueObjectModel model) =>
		new(new TypeIdentity(model.TypeModel.Name, model.TypeModel.Namespace));

	static ImmutableArray<AttributeDeclarationOptions> BuildTypeAttributes(ComplexValueObjectModel model)
	{
		return model.Options.GenerateJsonConverter && !model.HasJsonConverterAttribute
			?
			[
				new AttributeDeclarationOptions(TypeLibrary.System.Text.Json.Serialization.JsonConverterAttribute)
				{
					Arguments = [new($"typeof({model.TypeModel.Name}JsonConverter)")],
				},
			]
			: [];
	}

	static ImmutableArray<TypeReference> BuildInterfaces(ComplexValueObjectModel model)
	{
		var valueObjectType = ValueObjectType(model);

		var builder = ImmutableArray.CreateBuilder<TypeReference>();
		builder.Add(new TypeIdentity("IValueObject", "Purview.ValueObjects").MakeGeneric(valueObjectType));

		if (!model.IsReferenceType && !model.ImplementsSelfEquatable)
			builder.Add(new TypeIdentity("IEquatable", "System").MakeGeneric(valueObjectType));

		builder.Add(new TypeIdentity("IComparable", "System").MakeGeneric(valueObjectType));
		builder.Add(new TypeIdentity("IComparable", "System"));

		return builder.ToImmutable();
	}

	static void EmitOnNormalizeDeclaration(CodeWriter writer, ComplexValueObjectModel model)
	{
		if (!model.DeclareOnNormalize)
			return;

		writer.PartialMethod(
			new("OnNormalize")
			{
				IsStatic = true,
				Parameters =
				[
					.. model.Properties.Select(static property => new ParameterDeclarationOptions(
						ValueObjectSymbolInspector.ToCamelCase(property.Name),
						property.Type,
						ParameterModifier.Ref
					)),
				],
			}
		);
	}

	static void EmitCreateFactory(CodeWriter writer, ComplexValueObjectModel model)
	{
		if (model.CreateExists)
			return;

		var normalizeArgs = model
			.Properties.Select(property => $"ref {ValueObjectSymbolInspector.ToCamelCase(property.Name)}")
			.ToArray();

		writer.Method(
			new("Create", ValueObjectType(model), TypeDeclarationAccessibility.Public)
			{
				IsStatic = true,
				Parameters =
				[
					.. model.Properties.Select(static property => new ParameterDeclarationOptions(
						ValueObjectSymbolInspector.ToCamelCase(property.Name),
						property.Type
					)),
				],
			},
			body =>
			{
				body.MethodCall("OnNormalize", normalizeArgs);
				body.Assignment(
					"var",
					"result",
					new ObjectCreationOptions(
						ValueObjectType(model),
						[
							.. model.Properties.Select(static property => new MethodCallArgumentOptions(
								ValueObjectSymbolInspector.ToCamelCase(property.Name)
							)),
						]
					)
				);
				body.MethodCall(
					"result.OnValidate",
					[
						.. model.Properties.Select(static property =>
							ValueObjectSymbolInspector.ToCamelCase(property.Name)
						),
					]
				);
				body.Return("result");
			}
		);
	}

	static void EmitOnValidateDeclaration(CodeWriter writer, ComplexValueObjectModel model)
	{
		if (!model.DeclareOnValidate)
			return;

		writer.PartialMethod(
			new("OnValidate")
			{
				IsReadOnly = model.ValidateHookIsReadOnly,
				Attributes =
				[
					new(PurviewTypeLibrary.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute)
					{
						Arguments = [new("\"Performance\""), new("\"CA1822:Mark members as static\"")],
					},
				],
				Parameters =
				[
					.. model.Properties.Select(static property => new ParameterDeclarationOptions(
						ValueObjectSymbolInspector.ToCamelCase(property.Name),
						property.Type
					)),
				],
			}
		);
	}

	static void EmitHydrateFactory(CodeWriter writer, ComplexValueObjectModel model)
	{
		if (model.HydrateExists)
			return;

		var hydrateArgs = string.Join(
			", ",
			model.Properties.Select(static property => ValueObjectSymbolInspector.ToCamelCase(property.Name))
		);

		writer.Method(
			new("Hydrate", ValueObjectType(model), TypeDeclarationAccessibility.Public)
			{
				IsStatic = true,
				Parameters =
				[
					.. model.Properties.Select(static property => new ParameterDeclarationOptions(
						ValueObjectSymbolInspector.ToCamelCase(property.Name),
						property.Type
					)),
				],
			},
			body => body.Return($"new({hydrateArgs})")
		);
	}

	static void EmitEmpty(CodeWriter writer, ComplexValueObjectModel model)
	{
		if (!model.Options.GenerateEmpty || model.EmptyExists)
			return;

		writer.Property(
			new("Empty", ValueObjectType(model), TypeDeclarationAccessibility.Public)
			{
				IsStatic = true,
				ExpressionBody = $"Hydrate({string.Join(", ", model.EmptyArguments)})",
			}
		);
	}

	static void EmitConstructor(CodeWriter writer, ComplexValueObjectModel model)
	{
		if (model.CtorExists || model.Properties.IsEmpty)
			return;

		writer.Constructor(
			new ConstructorDeclarationOptions(model.TypeModel.Name, TypeDeclarationAccessibility.Private)
			{
				Parameters =
				[
					.. model.Properties.Select(static property => new ParameterDeclarationOptions(
						ValueObjectSymbolInspector.ToCamelCase(property.Name),
						property.Type
					)),
				],
			},
			body =>
			{
				foreach (var property in model.Properties)
					body.Assignment(property.Name, ValueObjectSymbolInspector.ToCamelCase(property.Name));
			}
		);
	}

	static void EmitEfConstructor(CodeWriter writer, ComplexValueObjectModel model)
	{
		if (!model.Options.GenerateConstructor || model.ParameterlessCtorExists || model.EfConstructorArguments is null)
			return;

		var accessibility = model.IsStruct ? TypeDeclarationAccessibility.Public : TypeDeclarationAccessibility.Private;

		writer.XmlSummary(
			"Parameterless constructor for EF Core deserialization.",
			"This constructor is required to work around EF Core's ConstructorBindingConvention,",
			"which cannot bind complex type parameters during JSON deserialization.",
			"EF Core uses this parameterless constructor to instantiate the value object,",
			"then sets properties directly from the JSON payload."
		);

		writer.Constructor(
			new(model.TypeModel.Name, accessibility) { Initializer = $"this({model.EfConstructorArguments})" },
			_ => { }
		);
	}
}
