namespace Purview.ValueObjects.SourceGenerator.ValueObject;

static partial class ScalarValueObjectEmitter
{
	public static void Emit(CodeWriter writer, ScalarValueObjectModel model)
	{
		writer.AutoGeneratedHeader();

		if (model.TypeModel.Namespace is not null)
			writer.FileScopedNamespace(model.TypeModel.Namespace);

		TypeDeclarationOptions declaration = new(model.TypeModel.Name, model.Accessibility)
		{
			Kind = GetTypeKind(model),
			IsPartial = true,
			IsSealed = false,
			IsReadOnly = model.IsReadOnly,
			Attributes = BuildTypeAttributes(model),
			Interfaces = BuildInterfaces(model),
		};

		writer.Type(declaration, body => EmitBody(body, model));
	}

	static void EmitBody(CodeWriter writer, ScalarValueObjectModel model)
	{
		EmitHookDeclarations(writer, model);
		EmitFactories(writer, model);
		EmitEmpty(writer, model);
		EmitTryCreate(writer, model);
		EmitComparison(writer, model);
		EmitConstructor(writer, model);
		EmitEnumProperties(writer, model);
		EmitEquality(writer, model);
		EmitOperators(writer, model);
		EmitConversions(writer, model);
		EmitToString(writer, model);
		EmitJsonConverter(writer, model);
	}

	static TypeDeclarationKind GetTypeKind(ScalarValueObjectModel model)
	{
		return model.IsRecord
			? model.IsReferenceType
				? TypeDeclarationKind.RecordClass
				: TypeDeclarationKind.RecordStruct
			: model.IsReferenceType
				? TypeDeclarationKind.Class
				: TypeDeclarationKind.Struct;
	}

	internal static TypeReference ValueObjectType(ScalarValueObjectModel model) =>
		new(new TypeIdentity(model.TypeModel.Name, model.TypeModel.Namespace));

	static ImmutableArray<AttributeDeclarationOptions> BuildTypeAttributes(ScalarValueObjectModel model)
	{
		return model.Options.GenerateJsonConverter && !model.HasJsonConverterAttribute
			?
			[
				new AttributeDeclarationOptions(TypeLibrary.System.Text.Json.Serialization.JsonConverterAttribute)
				{
					Arguments = [new($"typeof({model.TypeModel.Name}JsonConverter)")],
				},
			]
			: [];
	}

	static ImmutableArray<TypeReference> BuildInterfaces(ScalarValueObjectModel model)
	{
		var valueObjectType = ValueObjectType(model);

		var builder = ImmutableArray.CreateBuilder<TypeReference>();
		builder.Add(
			new TypeIdentity("IScalarValueObject", "Purview.ValueObjects").MakeGeneric(
				valueObjectType,
				model.ScalarTypeReference
			)
		);

		if (!model.IsReferenceType && !model.ImplementsSelfEquatable)
			builder.Add(new TypeIdentity("IEquatable", "System").MakeGeneric(valueObjectType));

		builder.Add(new TypeIdentity("IComparable", "System").MakeGeneric(valueObjectType));
		builder.Add(new TypeIdentity("IComparable", "System").MakeGeneric(model.ScalarTypeReference));
		builder.Add(new TypeIdentity("IComparable", "System"));

		return builder.ToImmutable();
	}

	static void EmitHookDeclarations(CodeWriter writer, ScalarValueObjectModel model)
	{
		if (model.DeclareOnNormalize)
		{
			writer.PartialMethod(
				new("OnNormalize")
				{
					IsStatic = true,
					Parameters = [new("value", model.ScalarTypeReference, ParameterModifier.Ref)],
				}
			);
		}

		if (model.DeclareOnValidate)
		{
			writer.PartialMethod(
				new("OnValidate") { IsStatic = true, Parameters = [new("value", model.ScalarTypeReference)] }
			);
		}
	}

	static void EmitFactories(CodeWriter writer, ScalarValueObjectModel model)
	{
		var valueObjectType = ValueObjectType(model);

		if (!model.CreateExists)
		{
			writer.Method(
				new("Create", valueObjectType, TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Parameters = [new("value", model.ScalarTypeReference)],
				},
				body =>
				{
					body.MethodCall("OnNormalize", "ref value");
					body.MethodCall("OnValidate", "value");
					body.Return("new(value)");
				}
			);
		}

		if (!model.HydrateExists)
		{
			writer.Method(
				new("Hydrate", valueObjectType, TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Parameters = [new("value", model.ScalarTypeReference)],
				},
				body => body.Return("new(value)")
			);
		}
	}

	static void EmitEmpty(CodeWriter writer, ScalarValueObjectModel model)
	{
		if (!model.Options.GenerateEmpty || model.EmptyExists)
			return;

		writer.Property(
			new("Empty", ValueObjectType(model), TypeDeclarationAccessibility.Public)
			{
				IsStatic = true,
				ExpressionBody = $"Hydrate({model.EmptyValueExpression})",
			}
		);
	}

	static void EmitTryCreate(CodeWriter writer, ScalarValueObjectModel model)
	{
		if (model.TryCreateExists)
			return;

		writer.Method(
			new("TryCreate", PurviewTypeLibrary.System.Boolean, TypeDeclarationAccessibility.Public)
			{
				IsStatic = true,
				Parameters =
				[
					new("value", model.ScalarTypeReference),
					new("result", ValueObjectType(model), ParameterModifier.Out),
				],
			},
			body =>
			{
				body.Block(
					"try",
					tryBlock =>
					{
						tryBlock.Assignment("result", "Create(value)");
						tryBlock.Return("true");
					}
				);
				body.Block(
					"catch (global::System.ArgumentException)",
					catchBlock =>
					{
						catchBlock.Assignment("result", "default!");
						catchBlock.Return("false");
					}
				);
			}
		);
	}

	static void EmitConstructor(CodeWriter writer, ScalarValueObjectModel model)
	{
		if (model.CtorExists)
			return;

		writer.Constructor(
			new(model.TypeModel.Name, TypeDeclarationAccessibility.Private)
			{
				Parameters = [new("value", model.ScalarTypeReference)],
			},
			body => body.Assignment(model.ScalarPropertyName, "value")
		);
	}

	static void EmitEnumProperties(CodeWriter writer, ScalarValueObjectModel model)
	{
		if (!model.EnumPropertiesEnabled)
			return;

		foreach (var enumFieldName in model.EnumFieldNames)
		{
			writer.Property(
				new(enumFieldName, ValueObjectType(model), TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					ExpressionBody = $"Hydrate({model.ScalarTypeName}.{enumFieldName})",
				}
			);
		}
	}
}
