namespace Purview.ValueObjects.SourceGenerator.ValueObject;

static partial class ScalarValueObjectEmitter
{
	public static void Emit(CodeWriter writer, ScalarValueObjectModel model, bool emitEF)
	{
		writer.AutoGeneratedHeader();

		if (model.TypeModel.Namespace is not null)
			writer.FileScopedNamespace(model.TypeModel.Namespace);

		TypeDeclarationOptions declaration = new(model.TypeModel.Name, model.Accessibility)
		{
			Kind = GetTypeKind(model),
			IsPartial = true,
			IsSealed = false,
			IsReadOnly = model.IsReadOnly,
			Attributes = BuildTypeAttributes(model),
			Interfaces = BuildInterfaces(model, emitEF),
		};

		writer.Type(declaration, body => EmitBody(body, model, emitEF));
	}

	static void EmitBody(CodeWriter writer, ScalarValueObjectModel model, bool emitEF)
	{
		EmitScalarProperty(writer, model);
		EmitHookDeclarations(writer, model);
		EmitScalarInterfaceValue(writer, model);
		EmitFactories(writer, model);
		EmitEmpty(writer, model);
		EmitTryCreate(writer, model);
		EmitComparison(writer, model);
		EmitConstructor(writer, model);
		EmitEnumProperties(writer, model);
		EmitEquality(writer, model);
		EmitOperators(writer, model);
		EmitConversions(writer, model);
		EmitToString(writer, model);
		EmitJsonConverter(writer, model);
		EmitEF(writer, model, emitEF);
	}

	static TypeDeclarationKind GetTypeKind(ScalarValueObjectModel model)
	{
		return model.IsRecord
			? model.IsReferenceType
				? TypeDeclarationKind.RecordClass
				: TypeDeclarationKind.RecordStruct
			: model.IsReferenceType
				? TypeDeclarationKind.Class
				: TypeDeclarationKind.Struct;
	}

	internal static TypeReference ValueObjectType(ScalarValueObjectModel model) =>
		new(new TypeIdentity(model.TypeModel.Name, model.TypeModel.Namespace));

	static ImmutableArray<AttributeDeclarationOptions> BuildTypeAttributes(ScalarValueObjectModel model)
	{
		return model.Options.GenerateJsonConverter && !model.HasJsonConverterAttribute
			?
			[
				new AttributeDeclarationOptions(TypeLibrary.System.Text.Json.Serialization.JsonConverterAttribute)
				{
					Arguments = [new($"typeof({model.TypeModel.Name}JsonConverter)")],
				},
			]
			: [];
	}

	static ImmutableArray<TypeReference> BuildInterfaces(ScalarValueObjectModel model, bool emitEF)
	{
		var valueObjectType = ValueObjectType(model);

		var builder = ImmutableArray.CreateBuilder<TypeReference>();
		builder.Add(
			TypeLibrary.Purview.ValueObjects.IScalarValueObject.MakeGeneric(valueObjectType, model.ScalarTypeReference)
		);

		if (!model.IsReferenceType && !model.ImplementsSelfEquatable)
			builder.Add(TypeLibrary.System.IEquatable.MakeGeneric(valueObjectType));

		builder.Add(TypeLibrary.System.IComparable.MakeGeneric(valueObjectType));
		builder.Add(TypeLibrary.System.IComparable.MakeGeneric(model.ScalarTypeReference));
		builder.Add(TypeLibrary.System.IComparable);

		// Expose the underlying value's formatting surface (for example a decimal's "N2") through the
		// generated ToString overload, but only when the scalar type actually supports it and the author has
		// not already implemented the interface.
		if (model.ScalarImplementsIFormattable && !model.FormattedToStringExists)
			builder.Add(TypeLibrary.System.IFormattable.AsTypeReference());

		if (emitEF && model.IsEFReferenced && (model.Options.GenerateEFConverter || model.Options.GenerateEFComparer))
			builder.Add(
				TypeLibrary.Purview.ValueObjects.IEFScalarValueObject.MakeGeneric(
					valueObjectType,
					model.ScalarTypeReference
				)
			);

		return builder.ToImmutable();
	}

	static void EmitHookDeclarations(CodeWriter writer, ScalarValueObjectModel model)
	{
		if (model.DeclareOnNormalize)
		{
			writer.PartialMethod(
				new("OnNormalize")
				{
					IsStatic = true,
					Parameters = [new("value", model.ScalarTypeReference, ParameterModifier.Ref)],
				}
			);
		}

		if (model.DeclareOnValidate)
		{
			writer.PartialMethod(
				new("OnValidate") { IsStatic = true, Parameters = [new("value", model.ScalarTypeReference)] }
			);
		}
	}

	static void EmitFactories(CodeWriter writer, ScalarValueObjectModel model)
	{
		var valueObjectType = ValueObjectType(model);

		if (!model.CreateExists)
		{
			writer.Method(
				new("Create", valueObjectType, TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Parameters = [new("value", model.ScalarTypeReference)],
				},
				body =>
				{
					body.MethodCall("OnNormalize", "ref value");

					if (model.HasZodSchemaValidation)
					{
						var schemaReference = GetZodSchemaReference(model);
						body.Assignment(
							"var",
							"instance",
							new ObjectCreationOptions(valueObjectType, [new MethodCallArgumentOptions("value")])
						);
						ValueObjectEmitterHelpers.ZodRefinement.EmitCreateValidation(body, schemaReference);

						if (model.Options.ZodSchemaMode != ValueObjectSymbolInspector.InsteadOfHooksModeName)
							body.MethodCall("OnValidate", "value");

						body.Return("instance");
					}
					else
					{
						body.MethodCall("OnValidate", "value");
						body.Return("new(value)");
					}
				}
			);
		}

		if (!model.HydrateExists)
		{
			writer.Method(
				new("Hydrate", valueObjectType, TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Parameters = [new("value", model.ScalarTypeReference)],
				},
				body => body.Return("new(value)")
			);
		}
	}

	internal static string GetZodSchemaReference(ScalarValueObjectModel model) =>
		model.TypeModel.Namespace is null
			? model.ZodSchemaClassName!
			: $"global::{model.TypeModel.Namespace}.{model.ZodSchemaClassName}";

	/// <summary>
	/// Declares the underlying property for the automatic <c>[Scalar&lt;T&gt;]</c> form. The manual form
	/// declares the property itself, so this emits nothing for it.
	/// </summary>
	/// <summary>
	/// The scalar type name safe to use in an <c>is</c> pattern. Neither a nullable-reference annotation nor
	/// a nullable value type is legal in a pattern (CS8116), so the trailing <c>?</c> is trimmed; a boxed
	/// value matches the underlying type either way.
	/// </summary>
	internal static string ScalarPatternTypeName(ScalarValueObjectModel model) => model.ScalarTypeName.TrimEnd('?');

	/// <summary>
	/// The argument to pass to the primitive comparison/equality overload from an <c>is</c> pattern. A
	/// nullable value type's pattern variable is the underlying non-nullable type, which is convertible to
	/// both the primitive overload and the value object (via the implicit-from-primitive operator), so it is
	/// cast to the scalar type to select the primitive overload unambiguously.
	/// </summary>
	internal static string ScalarPatternArgument(ScalarValueObjectModel model) =>
		model.ScalarValueIsNullable && !model.ScalarIsReferenceType
			? $"({model.ScalarTypeName})primitive"
			: "primitive";

	/// <summary>
	/// The parameter type for the primitive comparison overload. The BCL comparison interfaces annotate the
	/// parameter as nullable, so a reference scalar's parameter must be nullable too; a scalar whose
	/// underlying type is already a nullable reference keeps its single annotation.
	/// </summary>
	internal static TypeReference ScalarComparableParameter(ScalarValueObjectModel model, CodeWriter writer) =>
		model.ScalarIsReferenceType && !model.ScalarTypeIsNullableReference
			? model.ScalarTypeReference.Nullable(writer)
			: model.ScalarTypeReference;

	static void EmitScalarProperty(CodeWriter writer, ScalarValueObjectModel model)
	{
		if (!model.GenerateScalarProperty)
			return;

		writer.Property(
			new(model.ScalarPropertyName, model.ScalarTypeReference, TypeDeclarationAccessibility.Public)
			{
				HasSetter = true,
				IsInitOnly = true,
			}
		);
	}

	/// <summary>
	/// Satisfies <c>IScalarValueObject&lt;TSelf, TValue&gt;.Value</c> when the scalar member is named
	/// something else.
	/// </summary>
	/// <remarks>
	/// <see cref="BuildInterfaces"/> adds <c>IScalarValueObject&lt;TSelf, TValue&gt;</c> to every scalar
	/// value object, and that interface declares a member named <c>Value</c>. With
	/// <c>[Scalar("Amount")]</c> the author declares <c>Amount</c> and no <c>Value</c>, so without this
	/// the generated partial failed to compile with CS0535 — in generated code the consumer cannot edit.
	/// Forwarding keeps the author's chosen name as the primary accessor while honouring the contract
	/// the type already advertises; a consumer holding the interface sees <c>Value</c> regardless.
	/// </remarks>
	static void EmitScalarInterfaceValue(CodeWriter writer, ScalarValueObjectModel model)
	{
		if (string.Equals(model.ScalarPropertyName, "Value", StringComparison.Ordinal))
			return;

		writer.Property(
			new("Value", model.ScalarTypeReference, TypeDeclarationAccessibility.Public)
			{
				ExpressionBody = model.ScalarPropertyName,
			}
		);
	}

	static void EmitEmpty(CodeWriter writer, ScalarValueObjectModel model)
	{
		if (!model.Options.GenerateEmpty || model.EmptyExists)
			return;

		writer.Property(
			new("Empty", ValueObjectType(model), TypeDeclarationAccessibility.Public)
			{
				IsStatic = true,
				ExpressionBody = $"Hydrate({model.EmptyValueExpression})",
			}
		);
	}

	static void EmitTryCreate(CodeWriter writer, ScalarValueObjectModel model)
	{
		if (model.TryCreateExists)
			return;

		writer.Method(
			new("TryCreate", PurviewTypeLibrary.System.Boolean, TypeDeclarationAccessibility.Public)
			{
				IsStatic = true,
				Parameters =
				[
					new("value", model.ScalarTypeReference),
					new("result", ValueObjectType(model), ParameterModifier.Out),
				],
			},
			body =>
			{
				body.Block(
					"try",
					tryBlock =>
					{
						tryBlock.Assignment("result", "Create(value)");
						tryBlock.Return("true");
					}
				);
				body.Block(
					"catch (global::System.ArgumentException)",
					catchBlock =>
					{
						catchBlock.Assignment("result", "default!");
						catchBlock.Return("false");
					}
				);

				// A ZodSharp-validated Create throws ZodException, not ArgumentException, so without this
				// catch TryCreate threw for every [ZodSchema] value object instead of returning false —
				// the documented "try" contract did not hold for a headline feature.
				if (model.HasZodSchemaValidation)
				{
					body.Block(
						$"catch (global::{TypeLibrary.ZodExceptionTypeName})",
						catchBlock =>
						{
							catchBlock.Assignment("result", "default!");
							catchBlock.Return("false");
						}
					);
				}
			}
		);
	}

	static void EmitConstructor(CodeWriter writer, ScalarValueObjectModel model)
	{
		if (model.CtorExists)
			return;

		writer.Constructor(
			new(model.TypeModel.Name, TypeDeclarationAccessibility.Private)
			{
				Parameters = [new("value", model.ScalarTypeReference)],
			},
			body => body.Assignment(model.ScalarPropertyName, "value")
		);
	}

	static void EmitEnumProperties(CodeWriter writer, ScalarValueObjectModel model)
	{
		if (!model.EnumPropertiesEnabled)
			return;

		foreach (var enumFieldName in model.EnumFieldNames)
		{
			writer.Property(
				new(enumFieldName, ValueObjectType(model), TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					ExpressionBody = $"Hydrate({model.ScalarTypeName}.{enumFieldName})",
				}
			);
		}
	}
}
