using Microsoft.CodeAnalysis.Text;
using Purview.ValueObjects.SourceGenerator.Generators;

namespace Purview.ValueObjects.SourceGenerator.ValueObject;

static class ValueObjectsAttributeEmitter
{
	public static IEnumerable<(string HintName, SourceText Source)> EmitAttributes()
	{
		yield return (nameof(ValueObjectDefaultsAttribute) + ".g.cs", ValueObjectDefaultsAttribute());
	}

	static SourceText ValueObjectDefaultsAttribute()
	{
		var writer = GetCodeWriter();

		writer
			.XmlSummary(
				"Specifies assembly-level defaults for value object code generation.",
				$"These defaults can be overridden on individual {XmlSee(TypeLibrary.ValueObjectAttributeFullTypeName)} attributes."
			)
			.AttributeClass(
				new(TypeLibrary.Purview.ValueObjects.Serialization.ValueObjectDefaultsAttribute),
				AttributeTargets.Assembly,
				bodyWriter =>
				{
					bodyWriter
						.XmlSummary(
							$"Constructs a new instance of the {XmlSee(TypeLibrary.Purview.ValueObjects.Serialization.ValueObjectDefaultsAttribute)} class."
						)
						.Constructor(
							new(
								TypeLibrary.Purview.ValueObjects.Serialization.ValueObjectDefaultsAttribute,
								TypeDeclarationAccessibility.Public
							)
							{
								Parameters = [new("generateConstructor", PurviewTypeLibrary.System.Boolean) { }],
							},
							static ctor => ctor.Assignment("GenerateConstructor", "generateConstructor")
						);

					bodyWriter
						.XmlSummary(
							"Gets or sets whether parameterless constructors should be generated for value objects.",
							"When true, generates a private parameterless constructor for EF Core compatibility.",
							$"Individual {XmlSee(TypeLibrary.ValueObjectAttributeFullTypeName)} attributes can override this setting.",
							"Default: true"
						)
						.Property(
							new(
								"GenerateConstructor",
								PurviewTypeLibrary.System.Boolean,
								TypeDeclarationAccessibility.Public
							)
							{
								Initializer = "true",
							}
						);
				}
			);

		return writer;
	}

	static CodeWriter GetCodeWriter()
	{
		CodeWriter writer = new(SourceGenLibrary.CreateGenerationSettings<ValueObjectSourceGenerator>());

		return writer.AutoGeneratedHeader();
	}
}
