using Microsoft.CodeAnalysis.Text;
using Purview.ValueObjects.SourceGenerator.Generators;

namespace Purview.ValueObjects.SourceGenerator.ValueObject;

static class ValueObjectsAttributeEmitter
{
	public static IEnumerable<(string HintName, SourceText Source)> EmitAttributes()
	{
		yield return (nameof(ValueObjectDefaultsAttribute) + ".g.cs", ValueObjectDefaultsAttribute());
	}

	static SourceText ValueObjectDefaultsAttribute()
	{
		var writer = GetCodeWriter();

		writer
			.XmlSummary(
				"Specifies assembly-level defaults for value object code generation.",
				$"These defaults can be overridden on individual {XmlSee(TypeLibrary.ValueObjectAttributeFullTypeName)} and {XmlSee(TypeLibrary.ScalarAttributeFullTypeName)} attributes."
			)
			.AttributeClass(
				new(TypeLibrary.Purview.ValueObjects.Serialization.ValueObjectDefaultsAttribute),
				AttributeTargets.Assembly,
				bodyWriter =>
				{
					bodyWriter
						.XmlSummary(
							$"Constructs a new instance of the {XmlSee(TypeLibrary.Purview.ValueObjects.Serialization.ValueObjectDefaultsAttribute)} class."
						)
						.Constructor(
							new(
								TypeLibrary.Purview.ValueObjects.Serialization.ValueObjectDefaultsAttribute,
								TypeDeclarationAccessibility.Public
							),
							static _ => { }
						);

					EmitBoolProperty(
						bodyWriter,
						"GenerateJsonConverter",
						"Gets or sets whether a JSON converter should be generated by default."
					);
					EmitBoolProperty(
						bodyWriter,
						"GenerateComparable",
						"Gets or sets whether IComparable support should be generated by default."
					);
					EmitBoolProperty(
						bodyWriter,
						"GenerateComparisonOperators",
						"Gets or sets whether comparison operators should be generated by default."
					);
					EmitBoolProperty(
						bodyWriter,
						"GenerateEnumProperties",
						"Gets or sets whether enum properties should be generated from the underlying value by default."
					);
					EmitBoolProperty(
						bodyWriter,
						"GenerateImplicitFromPrimitive",
						"Gets or sets whether an implicit conversion from the primitive value should be generated by default."
					);
					EmitBoolProperty(
						bodyWriter,
						"GenerateImplicitToPrimitive",
						"Gets or sets whether an implicit conversion to the primitive value should be generated by default."
					);
					EmitBoolProperty(
						bodyWriter,
						"GenerateEmpty",
						"Gets or sets whether a static Empty instance should be generated by default."
					);
					EmitBoolProperty(
						bodyWriter,
						"GenerateConstructor",
						"Gets or sets whether parameterless constructors should be generated by default for [ValueObject] types.",
						"When true, generates a private parameterless constructor for EF Core compatibility."
					);
					EmitEnumProperty(
						bodyWriter,
						"DeserializationMode",
						TypeLibrary.Purview.ValueObjects.Serialization.ValueObjectDeserializationMode,
						"Purview.ValueObjects.Serialization.ValueObjectDeserializationMode.Hydrate",
						"Gets or sets the deserialization mode used by generated JSON converters by default."
					);
					EmitEnumProperty(
						bodyWriter,
						"ZodSchemaMode",
						TypeLibrary.Purview.ValueObjects.Serialization.ZodSchemaMode,
						"Purview.ValueObjects.Serialization.ZodSchemaMode.InAdditionToHooks",
						"Gets or sets how a source-generated ZodSharp schema validator participates in the generated Create path by default."
					);
				}
			);

		return writer;
	}

	static void EmitBoolProperty(CodeWriter bodyWriter, string name, params string[] summary)
	{
		bodyWriter
			.XmlSummary([.. summary, "Default: true"])
			.Property(
				new(name, PurviewTypeLibrary.System.Boolean, TypeDeclarationAccessibility.Public)
				{
					Initializer = "true",
				}
			);
	}

	static void EmitEnumProperty(
		CodeWriter bodyWriter,
		string name,
		TypeIdentity enumType,
		string defaultValue,
		params string[] summary
	)
	{
		bodyWriter
			.XmlSummary([.. summary, $"Default: {defaultValue.Split('.').Last()}"])
			.Property(new(name, enumType, TypeDeclarationAccessibility.Public) { Initializer = defaultValue });
	}

	static CodeWriter GetCodeWriter()
	{
		CodeWriter writer = new(SourceGenLibrary.CreateGenerationSettings<ValueObjectSourceGenerator>());

		return writer.AutoGeneratedHeader();
	}
}
