namespace Purview.ValueObjects.SourceGenerator.ValueObject;

/// <summary>
/// Emits the assembly-level <c>ValueObjectEFExtensions</c> registry that automatically maps every
/// Entity Framework Core-enabled value object in the compilation. The registry is generated only when
/// the consuming project references <c>Microsoft.EntityFrameworkCore</c> and contains at least one
/// opted-in value object.
/// </summary>
static class ValueObjectEFRegistryEmitter
{
	public static void Emit(
		CodeWriter writer,
		EquatableArray<EFScalarDescriptor> scalars,
		EquatableArray<EFComplexDescriptor> complex
	)
	{
		writer.AutoGeneratedHeader();
		writer.FileScopedNamespace(TypeLibrary.EFValueObjectEFNamespace);

		writer
			.Using("System")
			.Using("System.Collections.Generic")
			.Using("System.Linq")
			.Using("System.Reflection")
			.Using("Microsoft.EntityFrameworkCore.ChangeTracking")
			.Using("Microsoft.EntityFrameworkCore.Metadata")
			.Using("Microsoft.EntityFrameworkCore.Storage.ValueConversion");

		writer
			.XmlSummary(
				"Automatically configures Entity Framework Core mapping for value objects in this assembly.",
				"Call ConfigureValueObjects from OnModelCreating, or use UseValueObjects on the",
				"DbContextOptionsBuilder (e.g. AddDbContextFactory(o => o.UseSqlite(...).UseValueObjects()))",
				"to apply the mapping without overriding OnModelCreating. Scalar value objects are mapped to",
				"their underlying primitive column via a value converter; complex value objects are mapped as",
				"EF Core complex types (EF Core 8+) or JSON columns, depending on their",
				"[ValueObject(EFMapping = ...)] option."
			)
			.Class(
				new TypeDeclarationOptions(TypeLibrary.EFValueObjectExtensionsClassName)
				{
					Accessibility = TypeDeclarationAccessibility.Public,
					IsStatic = true,
					IsPartial = false,
					IncludeEmbeddedAttribute = true,
				},
				body =>
				{
					EmitMappingMethod(body, scalars, complex);
					EmitUseValueObjects(body);
					EmitHelperClass(body, "ScalarMapping", hasProviderMappable: true);
					EmitHelperClass(body, "JsonMapping", hasProviderMappable: false);
				}
			);

		EmitModelCustomizer(writer);
	}

	static void EmitUseValueObjects(CodeWriter writer)
	{
		var optionsBuilderType = TypeLibrary.Microsoft.EntityFrameworkCore.DbContextOptionsBuilder;
		var iModelCustomizerType = TypeLibrary.Microsoft.EntityFrameworkCore.Infrastructure.IModelCustomizer;

		writer
			.XmlSummary(
				"Configures the context so every value object in this assembly is mapped automatically.",
				"Use on the DbContextOptionsBuilder, for example:",
				"AddDbContextFactory&lt;T&gt;(options =&gt; options.UseSqlite(...).UseValueObjects()).",
				"This registers a ModelCustomizer that runs ConfigureValueObjects after OnModelCreating, so",
				"no OnModelCreating override is required."
			)
			.MethodExpression(
				new MethodDeclarationOptions("UseValueObjects", optionsBuilderType, TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Parameters = [new("optionsBuilder", optionsBuilderType) { IsThis = true }],
					ExpressionBody =
						$"optionsBuilder.ReplaceService<{iModelCustomizerType}, ValueObjectModelCustomizer>()",
				}
			);
	}

	static void EmitModelCustomizer(CodeWriter writer)
	{
		var modelCustomizerType = TypeLibrary.Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer;
		var modelCustomizerDependenciesType = TypeLibrary
			.Microsoft
			.EntityFrameworkCore
			.Infrastructure
			.ModelCustomizerDependencies;
		var modelBuilderType = TypeLibrary.Microsoft.EntityFrameworkCore.ModelBuilder;
		var dbContextType = TypeLibrary.Microsoft.EntityFrameworkCore.DbContext;

		writer
			.XmlSummary(
				"Applies value object mapping after OnModelCreating. Registered by UseValueObjects and",
				"used automatically when the context is created through AddDbContext, AddDbContextFactory or",
				"AddDbContextPool."
			)
			.Class(
				new TypeDeclarationOptions("ValueObjectModelCustomizer")
				{
					Accessibility = TypeDeclarationAccessibility.Public,
					IsSealed = true,
					IsPartial = false,
					BaseType = modelCustomizerType,
				},
				body =>
					body.Constructor(
							new ConstructorDeclarationOptions(
								"ValueObjectModelCustomizer",
								TypeDeclarationAccessibility.Public
							)
							{
								Parameters = [new("dependencies", modelCustomizerDependenciesType)],
								Initializer = "base(dependencies)",
							},
							_ => { }
						)
						.Method(
							new MethodDeclarationOptions(
								"Customize",
								PurviewTypeLibrary.System.Void,
								TypeDeclarationAccessibility.Public
							)
							{
								IsOverride = true,
								Parameters = [new("modelBuilder", modelBuilderType), new("context", dbContextType)],
							},
							method =>
							{
								method.MethodCall("Customize", ["modelBuilder", "context"], receiver: "base");
								method.MethodCall(
									"ConfigureValueObjects",
									Array.Empty<string>(),
									receiver: "modelBuilder"
								);
							}
						)
			);
	}

	static void EmitMappingMethod(
		CodeWriter writer,
		EquatableArray<EFScalarDescriptor> scalars,
		EquatableArray<EFComplexDescriptor> complex
	)
	{
		var scalarEntries = string.Join(
			", ",
			scalars.Select(static descriptor =>
				$"[typeof({descriptor.TypeName})] = new ScalarMapping({ConverterExpression(descriptor)}, {ComparerExpression(descriptor)}, {Bool(descriptor.ProviderMappable)})"
			)
		);
		var jsonEntries = string.Join(
			", ",
			complex
				.Where(static descriptor => descriptor.HasJsonConverter)
				.Select(static descriptor =>
					$"[typeof({descriptor.TypeName})] = new JsonMapping({JsonConverterExpression(descriptor)}, {ComparerExpression(descriptor)})"
				)
		);
		var complexTypes = complex
			.Where(static descriptor =>
				descriptor.EFMapping != null
				&& ValueObjectSymbolInspector.IsEFMappingComplexType(descriptor.EFMapping)
				&& descriptor.IsEF8Referenced
			)
			.Select(static descriptor => $"typeof({descriptor.TypeName})");

		writer.Method(
			new MethodDeclarationOptions("ConfigureValueObjects", TypeDeclarationAccessibility.Public)
			{
				IsStatic = true,
				Parameters =
				[
					new("modelBuilder", TypeLibrary.Microsoft.EntityFrameworkCore.ModelBuilder) { IsThis = true },
				],
			},
			method =>
			{
				method.Assignment(
					"var",
					"scalarMappings",
					$"new global::System.Collections.Generic.Dictionary<global::System.Type, ScalarMapping> {{ {scalarEntries} }}"
				);
				method.Assignment(
					"var",
					"jsonMappings",
					$"new global::System.Collections.Generic.Dictionary<global::System.Type, JsonMapping> {{ {jsonEntries} }}"
				);
				method.Assignment(
					"var",
					"complexTypeMappings",
					complexTypes.Any()
						? $"new[] {{ {string.Join(", ", complexTypes)} }}"
						: "global::System.Array.Empty<global::System.Type>()"
				);

				EmitScalarConversionLoop(method);
				EmitComplexMappingBlock(method);
			}
		);
	}

	static void EmitScalarConversionLoop(CodeWriter writer)
	{
		writer.Block(
			"foreach (var entityType in modelBuilder.Model.GetEntityTypes())",
			entityType =>
				entityType.Block(
					"foreach (var property in entityType.ClrType.GetProperties().Where(p => p.GetMethod is not null && !p.GetMethod.IsStatic))",
					property =>
						property.IfElse(
							"scalarMappings.TryGetValue(property.PropertyType, out var scalar) && scalar.Converter is not null && scalar.ProviderMappable",
							scalar => ApplyConverterAndComparer(writer, "scalar", "property"),
							elseBody =>
								elseBody.IfBlock(
									"jsonMappings.TryGetValue(property.PropertyType, out var json) && json.Converter is not null",
									json => ApplyConverterAndComparer(writer, "json", "property")
								)
						)
				)
		);
	}

	static void EmitComplexMappingBlock(CodeWriter writer)
	{
		writer.IfBlock(
			"complexTypeMappings.Length > 0",
			complex =>
			{
				complex.Block(
					"foreach (var entityType in modelBuilder.Model.GetEntityTypes())",
					entityType =>
						entityType.Block(
							"foreach (var property in entityType.ClrType.GetProperties().Where(p => p.GetMethod is not null && !p.GetMethod.IsStatic))",
							property =>
								property.IfBlock(
									"global::System.Array.IndexOf(complexTypeMappings, property.PropertyType) >= 0",
									isComplex =>
										isComplex.IfBlock(
											"!entityType.GetComplexProperties().Any(cp => cp.Name == property.Name)",
											notMapped =>
												notMapped.MethodCall(
													"ComplexProperty",
													["property.PropertyType", "property.Name"],
													receiver: "modelBuilder.Entity(entityType.ClrType!)"
												)
										)
								)
						)
				);

				complex.Block(
					"foreach (var entityType in modelBuilder.Model.GetEntityTypes())",
					entityType =>
						entityType.Block(
							"foreach (var complexProperty in entityType.GetComplexProperties())",
							complexProperty =>
								complexProperty.Block(
									"foreach (var member in complexProperty.ComplexType.ClrType.GetProperties().Where(p => p.GetMethod is not null && !p.GetMethod.IsStatic))",
									member => EmitComplexMember(member)
								)
						)
				);
			}
		);
	}

	static void ApplyConverterAndComparer(CodeWriter writer, string mappingName, string propertyName)
	{
		// The builder API is used so the property is configured regardless of convention discovery order.
		var builderExpression =
			$"modelBuilder.Entity({propertyName}.DeclaringType!).Property({propertyName}.PropertyType, {propertyName}.Name)";
		writer.IfElse(
			$"{mappingName}.Comparer is not null",
			withComparer =>
				withComparer.MethodCall(
					"HasConversion",
					[$"{mappingName}.Converter", $"{mappingName}.Comparer"],
					receiver: builderExpression
				),
			withoutComparer =>
				withoutComparer.MethodCall("HasConversion", [$"{mappingName}.Converter"], receiver: builderExpression)
		);
	}

	static void EmitComplexMember(CodeWriter writer)
	{
		// Every complex type member is declared explicitly so it maps to a column; nested scalar value
		// objects additionally receive a value conversion.
		var memberBuilder =
			"modelBuilder.Entity(entityType.ClrType!).ComplexProperty(complexProperty.ComplexType.ClrType, complexProperty.Name).Property(member.PropertyType, member.Name)";
		writer.Assignment("var", "memberBuilder", memberBuilder);
		writer.IfElse(
			"scalarMappings.TryGetValue(member.PropertyType, out var scalar) && scalar.Converter is not null && scalar.ProviderMappable",
			scalar =>
				scalar.IfElse(
					"scalar.Comparer is not null",
					withComparer =>
						withComparer.MethodCall(
							"HasConversion",
							["scalar.Converter", "scalar.Comparer"],
							receiver: "memberBuilder"
						),
					withoutComparer =>
						withoutComparer.MethodCall("HasConversion", ["scalar.Converter"], receiver: "memberBuilder")
				),
			elseBody =>
				elseBody.IfBlock(
					"jsonMappings.TryGetValue(member.PropertyType, out var json) && json.Converter is not null",
					json =>
						json.IfElse(
							"json.Comparer is not null",
							withComparer =>
								withComparer.MethodCall(
									"HasConversion",
									["json.Converter", "json.Comparer"],
									receiver: "memberBuilder"
								),
							withoutComparer =>
								withoutComparer.MethodCall(
									"HasConversion",
									["json.Converter"],
									receiver: "memberBuilder"
								)
						)
				)
		);
	}

	static void EmitHelperClass(CodeWriter writer, string className, bool hasProviderMappable)
	{
		var valueConverterType = TypeLibrary.Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter;
		var valueComparerType = TypeLibrary.Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer;

		writer.Class(
			new TypeDeclarationOptions(className)
			{
				Accessibility = TypeDeclarationAccessibility.Private,
				IsSealed = true,
				IsPartial = false,
			},
			body =>
			{
				var parameterList = ImmutableArray.CreateBuilder<ParameterDeclarationOptions>();
				parameterList.Add(new("converter", valueConverterType));
				parameterList.Add(new("comparer", valueComparerType.MakeNullable(writer)));
				if (hasProviderMappable)
					parameterList.Add(new("providerMappable", PurviewTypeLibrary.System.Boolean));

				body.Constructor(
						new ConstructorDeclarationOptions(className, TypeDeclarationAccessibility.Public)
						{
							Parameters = parameterList.ToImmutable(),
						},
						ctor =>
						{
							ctor.Assignment("Converter", "converter");
							ctor.Assignment("Comparer", "comparer");
							if (hasProviderMappable)
								ctor.Assignment("ProviderMappable", "providerMappable");
						}
					)
					.Property(
						new PropertyDeclarationOptions(
							"Converter",
							valueConverterType,
							TypeDeclarationAccessibility.Public
						)
						{
							HasGetter = true,
						}
					)
					.Property(
						new PropertyDeclarationOptions(
							"Comparer",
							valueComparerType.MakeNullable(writer),
							TypeDeclarationAccessibility.Public
						)
						{
							HasGetter = true,
						}
					);

				if (hasProviderMappable)
				{
					body.Property(
						new PropertyDeclarationOptions(
							"ProviderMappable",
							PurviewTypeLibrary.System.Boolean,
							TypeDeclarationAccessibility.Public
						)
						{
							HasGetter = true,
						}
					);
				}
			}
		);
	}

	static string ConverterExpression(EFScalarDescriptor descriptor) =>
		descriptor.HasConverter
			? descriptor.HasEFMembers
				? $"{descriptor.TypeName}.EF.Converter"
				: $"new global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<{descriptor.TypeName}, {descriptor.ProviderTypeName}>(vo => vo.{descriptor.ScalarPropertyName}, v => {descriptor.TypeName}.{descriptor.FactoryName}(v))"
			: "null";

	static string ComparerExpression(EFScalarDescriptor descriptor) =>
		descriptor.HasComparer
			? descriptor.HasEFMembers
				? $"{descriptor.TypeName}.EF.Comparer"
				: InlineComparerExpression(descriptor.TypeName)
			: "null";

	static string ComparerExpression(EFComplexDescriptor descriptor) =>
		descriptor.HasComparer
			? descriptor.HasEFMembers
				? $"{descriptor.TypeName}.EF.Comparer"
				: InlineComparerExpression(descriptor.TypeName)
			: "null";

	static string JsonConverterExpression(EFComplexDescriptor descriptor) =>
		descriptor.HasEFMembers
			? $"{descriptor.TypeName}.EF.Converter"
			: $"new global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<{descriptor.TypeName}, global::System.String>(vo => global::System.Text.Json.JsonSerializer.Serialize(vo), v => global::System.Text.Json.JsonSerializer.Deserialize<{descriptor.TypeName}>(v)!)";

	static string InlineComparerExpression(string typeName) =>
		$"new global::Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer<{typeName}>((a, b) => a == b, vo => vo.GetHashCode(), vo => vo)";

	static string Bool(bool value) => value ? "true" : "false";
}
