namespace Purview.ValueObjects.SourceGenerator.ValueObject;

/// <summary>
/// Emits the assembly-level <c>ValueObjectEFExtensions</c> registry that automatically maps every
/// Entity Framework Core-enabled value object in the compilation. The registry is generated only when
/// the consuming project references <c>Microsoft.EntityFrameworkCore</c> and contains at least one
/// opted-in value object.
/// </summary>
static class ValueObjectEFRegistryEmitter
{
	/// <summary>
	/// Emits the assembly-level registry. <paramref name="isEF8Referenced"/> tells the emitter whether the
	/// consuming project's Entity Framework Core reference is 8 or later: complex-type mapping and the
	/// compiled-model converter members both use APIs introduced there, so they are omitted below that so
	/// the generated code still compiles (the <c>VO1019</c> diagnostic explains the missing mapping).
	/// </summary>
	public static void Emit(
		CodeWriter writer,
		EquatableArray<EFScalarDescriptor> scalars,
		EquatableArray<EFComplexDescriptor> complex,
		bool isEF8Referenced
	)
	{
		writer.AutoGeneratedHeader();
		writer.FileScopedNamespace(TypeLibrary.EFValueObjectEFNamespace);

		var (scalarDefinition, scalarFields) = BuildInlineScalarConverters(scalars);
		var (inlineJsonDefinitions, inlineJsonFields) = BuildInlineJsonConverters(complex);
		var keyValueGenerators = BuildKeyValueGenerators(scalars);

		writer
			.Using("System")
			.Using("System.Collections.Generic")
			.Using("System.Linq")
			.Using("System.Reflection")
			.Using("Microsoft.EntityFrameworkCore.ChangeTracking")
			.Using("Microsoft.EntityFrameworkCore.Metadata")
			.Using("Microsoft.EntityFrameworkCore.Storage.ValueConversion");

		writer
			.XmlSummary(
				"Automatically configures Entity Framework Core mapping for value objects in this assembly.",
				"Call ConfigureValueObjects from OnModelCreating, or use UseValueObjects on the",
				"DbContextOptionsBuilder (e.g. AddDbContextFactory(o => o.UseSqlite(...).UseValueObjects()))",
				"to apply the mapping without overriding OnModelCreating. Scalar value objects are mapped to",
				"their underlying primitive column via a value converter; complex value objects are mapped as",
				"EF Core complex types (EF Core 8+) or JSON columns, depending on their",
				"[ValueObject(EFMapping = ...)] option."
			)
			.Class(
				new TypeDeclarationOptions(TypeLibrary.EFValueObjectExtensionsClassName)
				{
					Accessibility = TypeDeclarationAccessibility.Public,
					IsStatic = true,
					IsPartial = false,
					IncludeEmbeddedAttribute = true,
				},
				body =>
				{
					EmitMappingMethod(body, scalars, complex, scalarFields, inlineJsonFields, isEF8Referenced);
					EmitUseValueObjects(body);
					if (!keyValueGenerators.IsDefaultOrEmpty)
						EmitUseValueObjectKeyGenerators(body);
					EmitInlineConverterFields(body, scalarDefinition);
					EmitInlineConverterFields(body, inlineJsonDefinitions);
					EmitHelperClass(body, "ScalarMapping", hasProviderMappable: true);
					EmitHelperClass(body, "JsonMapping", hasProviderMappable: false);
					EmitInlineConverters(body, scalarDefinition, isEF8Referenced);
					EmitInlineConverters(body, inlineJsonDefinitions, isEF8Referenced);
					EmitInlineKeyValueGenerators(body, keyValueGenerators, isEF8Referenced);
				}
			);

		EmitModelCustomizer(writer);

		if (!keyValueGenerators.IsDefaultOrEmpty)
		{
			EmitKeyOrderingEnum(writer);
			EmitSequentialGuidClass(writer);
			EmitKeyValueGeneratorConventionClass(writer, keyValueGenerators);
		}
	}

	/// <summary>Emits the enum that selects which ordering generated key values ascend in.</summary>
	static void EmitKeyOrderingEnum(CodeWriter writer)
	{
		writer
			.XmlSummary(
				"Selects the ordering generated key values ascend in.",
				"Pass it to ValueObjectEFExtensions.UseValueObjectKeyGenerators to override the default."
			)
			.Enum(
				TypeLibrary.EFKeyOrderingEnumName,
				TypeDeclarationAccessibility.Public,
				fields:
				[
					new EnumFieldDeclarationOptions(
						"UuidV7",
						0,
						[
							"Millisecond-precision time-ordered (RFC 9562 version 7) identifiers.",
							"Values ascend by creation time in any store that compares the identifier's",
							"sixteen bytes big-endian, such as PostgreSQL, SQLite, or MySQL.",
						]
					),
					new EnumFieldDeclarationOptions(
						"SqlServer",
						1,
						[
							"Identifiers that ascend by creation time in SQL Server's uniqueidentifier",
							"ordering, which compares the trailing six bytes first. Use it for clustered",
							"SQL Server keys to avoid index fragmentation; everywhere else the default is",
							"preferable because the value is no longer a well-formed version 7 UUID.",
						]
					),
				]
			);
	}

	static void EmitUseValueObjects(CodeWriter writer)
	{
		var optionsBuilderType = TypeLibrary.Microsoft.EntityFrameworkCore.DbContextOptionsBuilder;
		var iModelCustomizerType = TypeLibrary.Microsoft.EntityFrameworkCore.Infrastructure.IModelCustomizer;

		writer
			.XmlSummary(
				"Configures the context so every value object in this assembly is mapped automatically.",
				"Use on the DbContextOptionsBuilder, for example:",
				"AddDbContextFactory&lt;T&gt;(options =&gt; options.UseSqlite(...).UseValueObjects()).",
				"This registers a ModelCustomizer that runs ConfigureValueObjects after OnModelCreating, so",
				"no OnModelCreating override is required."
			)
			.MethodExpression(
				new MethodDeclarationOptions("UseValueObjects", optionsBuilderType, TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Parameters = [new("optionsBuilder", optionsBuilderType) { IsThis = true }],
					ExpressionBody =
						$"optionsBuilder.ReplaceService<{iModelCustomizerType}, ValueObjectModelCustomizer>()",
				}
			);
	}

	static void EmitModelCustomizer(CodeWriter writer)
	{
		var modelCustomizerType = TypeLibrary.Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer;
		var modelCustomizerDependenciesType = TypeLibrary
			.Microsoft
			.EntityFrameworkCore
			.Infrastructure
			.ModelCustomizerDependencies;
		var modelBuilderType = TypeLibrary.Microsoft.EntityFrameworkCore.ModelBuilder;
		var dbContextType = TypeLibrary.Microsoft.EntityFrameworkCore.DbContext;

		writer
			.XmlSummary(
				"Applies value object mapping after OnModelCreating. Registered by UseValueObjects and",
				"used automatically when the context is created through AddDbContext, AddDbContextFactory or",
				"AddDbContextPool."
			)
			.Class(
				new TypeDeclarationOptions("ValueObjectModelCustomizer")
				{
					Accessibility = TypeDeclarationAccessibility.Public,
					IsSealed = true,
					IsPartial = false,
					BaseType = modelCustomizerType,
				},
				body =>
					body.Constructor(
							new ConstructorDeclarationOptions(
								"ValueObjectModelCustomizer",
								TypeDeclarationAccessibility.Public
							)
							{
								Parameters = [new("dependencies", modelCustomizerDependenciesType)],
								Initializer = "base(dependencies)",
							},
							_ => { }
						)
						.Method(
							new MethodDeclarationOptions(
								"Customize",
								PurviewTypeLibrary.System.Void,
								TypeDeclarationAccessibility.Public
							)
							{
								IsOverride = true,
								Parameters = [new("modelBuilder", modelBuilderType), new("context", dbContextType)],
							},
							method =>
							{
								method.MethodCall("Customize", ["modelBuilder", "context"], receiver: "base");
								method.MethodCall(
									"ConfigureValueObjects",
									Array.Empty<string>(),
									receiver: "modelBuilder"
								);
							}
						)
			);
	}

	static void EmitMappingMethod(
		CodeWriter writer,
		EquatableArray<EFScalarDescriptor> scalars,
		EquatableArray<EFComplexDescriptor> complex,
		IReadOnlyDictionary<EFScalarDescriptor, string> inlineScalarConverters,
		IReadOnlyDictionary<EFComplexDescriptor, string> inlineJsonConverters,
		bool isEF8Referenced
	)
	{
		var scalarEntries = string.Join(
			", ",
			scalars.Select(descriptor =>
				$"[typeof({descriptor.TypeName})] = new ScalarMapping({ConverterExpression(descriptor, inlineScalarConverters)}, {ComparerExpression(descriptor)}, {Bool(descriptor.ProviderMappable)})"
			)
		);
		var jsonEntries = string.Join(
			", ",
			complex
				.Where(static descriptor => descriptor.HasJsonConverter)
				.Select(descriptor =>
					$"[typeof({descriptor.TypeName})] = new JsonMapping({JsonConverterExpression(descriptor, inlineJsonConverters)}, {ComparerExpression(descriptor)})"
				)
		);
		var complexTypes = complex
			.Where(static descriptor =>
				descriptor.EFMapping != null
				&& ValueObjectSymbolInspector.IsEFMappingComplexType(descriptor.EFMapping)
				&& descriptor.IsEF8Referenced
			)
			.Select(static descriptor => $"typeof({descriptor.TypeName})");

		writer.Method(
			new MethodDeclarationOptions("ConfigureValueObjects", TypeDeclarationAccessibility.Public)
			{
				IsStatic = true,
				Parameters =
				[
					new("modelBuilder", TypeLibrary.Microsoft.EntityFrameworkCore.ModelBuilder) { IsThis = true },
				],
			},
			method =>
			{
				method.Assignment(
					"var",
					"scalarMappings",
					$"new global::System.Collections.Generic.Dictionary<global::System.Type, ScalarMapping> {{ {scalarEntries} }}"
				);
				method.Assignment(
					"var",
					"jsonMappings",
					$"new global::System.Collections.Generic.Dictionary<global::System.Type, JsonMapping> {{ {jsonEntries} }}"
				);

				// Complex types and the compiled-model APIs the block relies on arrived in Entity Framework
				// Core 8, so below that neither the mapping list nor the block is emitted.
				if (isEF8Referenced)
				{
					method.Assignment(
						"var",
						"complexTypeMappings",
						complexTypes.Any()
							? $"new[] {{ {string.Join(", ", complexTypes)} }}"
							: "global::System.Array.Empty<global::System.Type>()"
					);
				}

				EmitScalarConversionLoop(method);

				if (isEF8Referenced)
					EmitComplexMappingBlock(method);
			}
		);
	}

	/// <summary>
	/// Emits the predicate deciding which CLR properties the registry may configure.
	/// </summary>
	/// <remarks>
	/// <para>
	/// The loop below configures a property with <c>modelBuilder.Entity(t).Property(type, name)</c>, which is
	/// <em>explicit</em> configuration and therefore outranks <c>[NotMapped]</c> and <c>Ignore(...)</c>. The
	/// predicate used to be "has a non-static getter", so the registry pulled deliberately excluded members
	/// back into the model — an unasked-for column and migration — and, for a computed setter-less property,
	/// broke the model outright: Entity Framework Core's own validation fails with "No backing field could be
	/// found ... and the property does not have a setter", so the whole <c>DbContext</c> would not build.
	/// </para>
	/// <para>
	/// Emitted as a local function rather than inlined so the rule exists once and is readable in the
	/// generated output.
	/// </para>
	/// </remarks>
	static void EmitMappablePropertyPredicate(CodeWriter writer)
	{
		writer.Block(
			"static bool IsMappableValueObjectProperty("
				+ "global::Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType entityType, "
				+ "global::System.Reflection.PropertyInfo property)",
			body =>
			{
				body.Line("// Not readable, or not an instance member: never mapped.")
					.Line("if (property.GetMethod is null || property.GetMethod.IsStatic)")
					.Line("\treturn false;")
					.Line("")
					.Line("// The author excluded it with [NotMapped].")
					.Line(
						"if (global::System.Reflection.CustomAttributeExtensions"
							+ ".GetCustomAttribute<global::System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute>"
							+ "(property) is not null)"
					)
					.Line("\treturn false;")
					.Line("")
					.Line("// The author excluded it with modelBuilder.Entity<T>().Ignore(...).")
					.Line(
						"if (((global::Microsoft.EntityFrameworkCore.Metadata.IConventionEntityType)entityType)"
							+ ".FindIgnoredConfigurationSource(property.Name) is not null)"
					)
					.Line("\treturn false;")
					.Line("")
					.Line("// Computed and setter-less: there is nowhere to materialize into, and configuring it")
					.Line("// fails Entity Framework Core's field-mapping validation. A get-only auto-property is")
					.Line("// different - it has a compiler-generated backing field, which EF maps - so the check is")
					.Line("// for that field rather than merely for a missing setter.")
					.Line("if (property.SetMethod is null && property.DeclaringType is { } declaringType")
					.Line(
						"\t&& declaringType.GetField($\"<{property.Name}>k__BackingField\", "
							+ "global::System.Reflection.BindingFlags.Instance | "
							+ "global::System.Reflection.BindingFlags.NonPublic) is null)"
					)
					.Line("\treturn false;")
					.Line("")
					.Line("return true;");
			}
		);
	}

	static void EmitScalarConversionLoop(CodeWriter writer)
	{
		EmitMappablePropertyPredicate(writer);

		// The entity types are snapshotted: configuring a property adds it to the model, and an enumerator
		// over the live collection throws as soon as the set of entity types changes underneath it.
		writer.Block(
			"foreach (var entityType in modelBuilder.Model.GetEntityTypes().ToList())",
			entityType =>
				entityType.Block(
					"foreach (var property in entityType.ClrType.GetProperties().Where(p => IsMappableValueObjectProperty(entityType, p)))",
					property =>
						property.IfElse(
							"scalarMappings.TryGetValue(property.PropertyType, out var scalar) && scalar.Converter is not null && scalar.ProviderMappable",
							scalar => ApplyConverterAndComparer(writer, "scalar", "property", "entityType.ClrType!"),
							elseBody =>
								elseBody.IfBlock(
									"jsonMappings.TryGetValue(property.PropertyType, out var json) && json.Converter is not null",
									json => ApplyConverterAndComparer(writer, "json", "property", "entityType.ClrType!")
								)
						)
				)
		);
	}

	static void EmitComplexMappingBlock(CodeWriter writer)
	{
		writer.IfBlock(
			"complexTypeMappings.Length > 0",
			complex =>
			{
				// Declaring a complex property can add complex types to the model, so the entity types are
				// snapshotted before the loop mutates the model it is walking.
				complex.Block(
					"foreach (var entityType in modelBuilder.Model.GetEntityTypes().ToList())",
					entityType =>
						entityType.Block(
							"foreach (var property in entityType.ClrType.GetProperties().Where(p => p.GetMethod is not null && !p.GetMethod.IsStatic))",
							property =>
								property.IfBlock(
									"global::System.Array.IndexOf(complexTypeMappings, property.PropertyType) >= 0",
									isComplex =>
										isComplex.IfBlock(
											"!entityType.GetComplexProperties().Any(cp => cp.Name == property.Name)",
											notMapped =>
												notMapped.MethodCall(
													"ComplexProperty",
													["property.PropertyType", "property.Name"],
													receiver: "modelBuilder.Entity(entityType.ClrType!)"
												)
										)
								)
						)
				);

				complex.Block(
					"foreach (var entityType in modelBuilder.Model.GetEntityTypes().ToList())",
					entityType =>
						entityType.Block(
							"foreach (var complexProperty in entityType.GetComplexProperties())",
							complexProperty =>
								complexProperty.Block(
									"foreach (var member in complexProperty.ComplexType.ClrType.GetProperties().Where(p => p.GetMethod is not null && !p.GetMethod.IsStatic))",
									member => EmitComplexMember(member)
								)
						)
				);
			}
		);
	}

	/// <summary>
	/// Applies the mapping's converter and comparer to an entity property.
	/// </summary>
	/// <param name="writer">The writer for the generated method body.</param>
	/// <param name="mappingName">The name of the mapping local holding the converter and comparer.</param>
	/// <param name="propertyName">The name of the property local being configured.</param>
	/// <param name="entityTypeExpression">
	/// The expression for the entity type being configured. The property's declaring type cannot be used: an
	/// inherited property is declared by a base type that is usually not an entity type at all, and asking the
	/// model builder for it would add a new entity type while the registry is walking the model.
	/// </param>
	static void ApplyConverterAndComparer(
		CodeWriter writer,
		string mappingName,
		string propertyName,
		string entityTypeExpression
	)
	{
		// The builder API is used so the property is configured regardless of convention discovery order.
		var builderExpression =
			$"modelBuilder.Entity({entityTypeExpression}).Property({propertyName}.PropertyType, {propertyName}.Name)";
		writer.IfElse(
			$"{mappingName}.Comparer is not null",
			withComparer =>
				withComparer.MethodCall(
					"HasConversion",
					[$"{mappingName}.Converter", $"{mappingName}.Comparer"],
					receiver: builderExpression
				),
			withoutComparer =>
				withoutComparer.MethodCall("HasConversion", [$"{mappingName}.Converter"], receiver: builderExpression)
		);
	}

	static void EmitComplexMember(CodeWriter writer)
	{
		// Every complex type member is declared explicitly so it maps to a column; nested scalar value
		// objects additionally receive a value conversion.
		var memberBuilder =
			"modelBuilder.Entity(entityType.ClrType!).ComplexProperty(complexProperty.ComplexType.ClrType, complexProperty.Name).Property(member.PropertyType, member.Name)";
		writer.Assignment("var", "memberBuilder", memberBuilder);
		writer.IfElse(
			"scalarMappings.TryGetValue(member.PropertyType, out var scalar) && scalar.Converter is not null && scalar.ProviderMappable",
			scalar =>
				scalar.IfElse(
					"scalar.Comparer is not null",
					withComparer =>
						withComparer.MethodCall(
							"HasConversion",
							["scalar.Converter", "scalar.Comparer"],
							receiver: "memberBuilder"
						),
					withoutComparer =>
						withoutComparer.MethodCall("HasConversion", ["scalar.Converter"], receiver: "memberBuilder")
				),
			elseBody =>
				elseBody.IfBlock(
					"jsonMappings.TryGetValue(member.PropertyType, out var json) && json.Converter is not null",
					json =>
						json.IfElse(
							"json.Comparer is not null",
							withComparer =>
								withComparer.MethodCall(
									"HasConversion",
									["json.Converter", "json.Comparer"],
									receiver: "memberBuilder"
								),
							withoutComparer =>
								withoutComparer.MethodCall(
									"HasConversion",
									["json.Converter"],
									receiver: "memberBuilder"
								)
						)
				)
		);
	}

	static void EmitHelperClass(CodeWriter writer, string className, bool hasProviderMappable)
	{
		var valueConverterType = TypeLibrary.Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter;
		var valueComparerType = TypeLibrary.Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer;

		writer.Class(
			new TypeDeclarationOptions(className)
			{
				Accessibility = TypeDeclarationAccessibility.Private,
				IsSealed = true,
				IsPartial = false,
			},
			body =>
			{
				var parameterList = ImmutableArray.CreateBuilder<ParameterDeclarationOptions>();
				parameterList.Add(new("converter", valueConverterType));
				parameterList.Add(new("comparer", valueComparerType.MakeNullable(writer)));
				if (hasProviderMappable)
					parameterList.Add(new("providerMappable", PurviewTypeLibrary.System.Boolean));

				body.Constructor(
						new ConstructorDeclarationOptions(className, TypeDeclarationAccessibility.Public)
						{
							Parameters = parameterList.ToImmutable(),
						},
						ctor =>
						{
							ctor.Assignment("Converter", "converter");
							ctor.Assignment("Comparer", "comparer");
							if (hasProviderMappable)
								ctor.Assignment("ProviderMappable", "providerMappable");
						}
					)
					.Property(
						new PropertyDeclarationOptions(
							"Converter",
							valueConverterType,
							TypeDeclarationAccessibility.Public
						)
						{
							HasGetter = true,
						}
					)
					.Property(
						new PropertyDeclarationOptions(
							"Comparer",
							valueComparerType.MakeNullable(writer),
							TypeDeclarationAccessibility.Public
						)
						{
							HasGetter = true,
						}
					);

				if (hasProviderMappable)
				{
					body.Property(
						new PropertyDeclarationOptions(
							"ProviderMappable",
							PurviewTypeLibrary.System.Boolean,
							TypeDeclarationAccessibility.Public
						)
						{
							HasGetter = true,
						}
					);
				}
			}
		);
	}

	static string ConverterExpression(
		EFScalarDescriptor descriptor,
		IReadOnlyDictionary<EFScalarDescriptor, string> inlineConverters
	) =>
		descriptor.HasConverter
			? descriptor.HasEFMembers
				? $"{descriptor.TypeName}.EF.Converter"
				: inlineConverters[descriptor]
			: "null";

	static string ComparerExpression(EFScalarDescriptor descriptor) =>
		descriptor.HasComparer
			? descriptor.HasEFMembers
				? $"{descriptor.TypeName}.EF.Comparer"
				: InlineComparerExpression(descriptor.TypeName)
			: "null";

	static string ComparerExpression(EFComplexDescriptor descriptor) =>
		descriptor.HasComparer
			? descriptor.HasEFMembers
				? $"{descriptor.TypeName}.EF.Comparer"
				: InlineComparerExpression(descriptor.TypeName)
			: "null";

	static string JsonConverterExpression(
		EFComplexDescriptor descriptor,
		IReadOnlyDictionary<EFComplexDescriptor, string> inlineConverters
	) => descriptor.HasEFMembers ? $"{descriptor.TypeName}.EF.Converter" : inlineConverters[descriptor];

	static string InlineComparerExpression(string typeName) =>
		$"new global::Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer<{typeName}>((a, b) => a == b, vo => vo.GetHashCode(), vo => vo)";

	static string Bool(bool value) => value ? "true" : "false";

	/// <summary>
	/// Builds a nested converter class and a shared instance field for each scalar value object that has no
	/// <c>EF</c> members of its own — a value object declared in an assembly that does not reference Entity
	/// Framework Core, mapped inline by this registry.
	/// </summary>
	static (
		ImmutableArray<InlineConverterDefinition> Definitions,
		Dictionary<EFScalarDescriptor, string> Fields
	) BuildInlineScalarConverters(EquatableArray<EFScalarDescriptor> scalars)
	{
		var definitions = ImmutableArray.CreateBuilder<InlineConverterDefinition>();
		Dictionary<EFScalarDescriptor, string> fields = [];
		HashSet<string> usedNames = new(StringComparer.Ordinal);

		foreach (var descriptor in scalars)
		{
			if (!descriptor.HasConverter || descriptor.HasEFMembers)
				continue;

			var providerTypeName = descriptor.EFProviderTypeName!;
			var hydrateCastTypeName = descriptor.EFHydrateCastTypeName;
			var className = UniqueName(SanitizeIdentifier(descriptor.TypeName) + "Converter", usedNames);
			var fieldName = "_" + className;

			definitions.Add(
				new InlineConverterDefinition(
					className,
					fieldName,
					ValueObjectEmitterHelpers.EFConverterBaseType(descriptor.TypeName, providerTypeName),
					descriptor.TypeName,
					providerTypeName,
					ValueObjectEFConverterEmitter.ToProviderExpression(
						descriptor.ScalarPropertyName!,
						hydrateCastTypeName is null ? null : providerTypeName
					),
					ValueObjectEFConverterEmitter.FromProviderExpression(descriptor.TypeName, hydrateCastTypeName)
				)
			);
			fields[descriptor] = fieldName;
		}

		return (definitions.ToImmutable(), fields);
	}

	/// <summary>
	/// Builds a nested converter class and a shared instance field for each JSON-mapped complex value object
	/// that has no <c>EF</c> members of its own.
	/// </summary>
	static (
		ImmutableArray<InlineConverterDefinition> Definitions,
		Dictionary<EFComplexDescriptor, string> Fields
	) BuildInlineJsonConverters(EquatableArray<EFComplexDescriptor> complex)
	{
		var definitions = ImmutableArray.CreateBuilder<InlineConverterDefinition>();
		Dictionary<EFComplexDescriptor, string> fields = [];
		HashSet<string> usedNames = new(StringComparer.Ordinal);

		foreach (var descriptor in complex)
		{
			if (!descriptor.HasJsonConverter || descriptor.HasEFMembers)
				continue;

			var className = UniqueName(SanitizeIdentifier(descriptor.TypeName) + "JsonConverter", usedNames);
			var fieldName = "_" + className;

			definitions.Add(
				new InlineConverterDefinition(
					className,
					fieldName,
					ValueObjectEmitterHelpers.EFConverterBaseType(descriptor.TypeName, "global::System.String"),
					descriptor.TypeName,
					"global::System.String",
					"vo => global::System.Text.Json.JsonSerializer.Serialize(vo)",
					$"v => global::System.Text.Json.JsonSerializer.Deserialize<{descriptor.TypeName}>(v)!"
				)
			);
			fields[descriptor] = fieldName;
		}

		return (definitions.ToImmutable(), fields);
	}

	/// <summary>
	/// Builds the key value generator mappings: value objects that opted in with
	/// <c>GenerateEFValueGenerator</c>, paired with the factory type Entity Framework Core instantiates.
	/// </summary>
	static ImmutableArray<KeyValueGeneratorMapping> BuildKeyValueGenerators(EquatableArray<EFScalarDescriptor> scalars)
	{
		var mappings = ImmutableArray.CreateBuilder<KeyValueGeneratorMapping>();
		HashSet<string> usedNames = new(StringComparer.Ordinal);

		foreach (var descriptor in scalars)
		{
			if (!descriptor.GenerateEFValueGenerator)
				continue;

			if (descriptor.HasEFMembers)
			{
				mappings.Add(
					new KeyValueGeneratorMapping(
						descriptor.TypeName,
						$"{descriptor.TypeName}.EF.{TypeLibrary.EFValueGeneratorFactoryMemberName}",
						$"{descriptor.TypeName}.EF.{TypeLibrary.EFValueGeneratorSqlServerFactoryMemberName}",
						InlineGeneratorClassName: null,
						InlineFactoryClassName: null,
						InlineSqlServerGeneratorClassName: null,
						InlineSqlServerFactoryClassName: null
					)
				);
				continue;
			}

			// The declaring assembly does not reference Entity Framework Core, so the generator pairs are
			// emitted into this registry alongside the inline converters.
			var generatorClassName = UniqueName(SanitizeIdentifier(descriptor.TypeName) + "ValueGenerator", usedNames);
			var factoryClassName = UniqueName(
				SanitizeIdentifier(descriptor.TypeName) + "ValueGeneratorFactory",
				usedNames
			);
			var sqlServerGeneratorClassName = UniqueName(
				SanitizeIdentifier(descriptor.TypeName) + "SqlServerValueGenerator",
				usedNames
			);
			var sqlServerFactoryClassName = UniqueName(
				SanitizeIdentifier(descriptor.TypeName) + "SqlServerValueGeneratorFactory",
				usedNames
			);
			mappings.Add(
				new KeyValueGeneratorMapping(
					descriptor.TypeName,
					$"{TypeLibrary.EFValueObjectExtensionsClassName}.{factoryClassName}",
					$"{TypeLibrary.EFValueObjectExtensionsClassName}.{sqlServerFactoryClassName}",
					generatorClassName,
					factoryClassName,
					sqlServerGeneratorClassName,
					sqlServerFactoryClassName
				)
			);
		}

		return mappings.ToImmutable();
	}

	/// <summary>Emits the registration extensions for the generated key value generator convention.</summary>
	static void EmitUseValueObjectKeyGenerators(CodeWriter body)
	{
		TypeReference modelConfigurationBuilder = new(
			new TypeIdentity(TypeLibrary.EFModelConfigurationBuilderFullTypeName, null)
		);
		TypeReference ordering = new(new TypeIdentity(TypeLibrary.EFKeyOrderingEnumFullTypeName, null));

		body.XmlSummary(
				"Registers the generated key value generator convention with the default UUIDv7 ordering.",
				"Call it from ConfigureConventions so a key property typed as a value object that opted in with",
				"GenerateEFValueGenerator receives a time-ordered identifier when it is left unset. Convention-level",
				"configuration is the lowest precedence, so an explicit entity configuration always wins."
			)
			.MethodExpression(
				new MethodDeclarationOptions(
					"UseValueObjectKeyGenerators",
					modelConfigurationBuilder,
					TypeDeclarationAccessibility.Public
				)
				{
					IsStatic = true,
					Parameters = [new("configurationBuilder", modelConfigurationBuilder) { IsThis = true }],
					ExpressionBody =
						$"configurationBuilder.UseValueObjectKeyGenerators({TypeLibrary.EFKeyOrderingEnumName}.UuidV7)",
				}
			)
			.XmlSummary(
				"Registers the generated key value generator convention with the given key ordering.",
				$"{TypeLibrary.EFKeyOrderingEnumName}.UuidV7 sorts by creation time where the store compares",
				"identifiers byte by byte - PostgreSQL, SQLite, MySQL, and non-clustered SQL Server keys.",
				$"{TypeLibrary.EFKeyOrderingEnumName}.SqlServer produces values that ascend in SQL Server's",
				"uniqueidentifier ordering instead, which keeps a clustered SQL Server key from fragmenting.",
				"Either way the identifier is created in process without a database round trip."
			)
			.Method(
				new MethodDeclarationOptions(
					"UseValueObjectKeyGenerators",
					modelConfigurationBuilder,
					TypeDeclarationAccessibility.Public
				)
				{
					IsStatic = true,
					Parameters =
					[
						new("configurationBuilder", modelConfigurationBuilder) { IsThis = true },
						new("ordering", ordering),
					],
				},
				method =>
				{
					method.MethodCall(
						"configurationBuilder.Conventions.Add",
						$"_ => new {TypeLibrary.EFKeyValueGeneratorConventionClassName}(ordering)"
					);
					method.Return("configurationBuilder");
				}
			);
	}

	static void EmitInlineKeyValueGenerators(
		CodeWriter body,
		ImmutableArray<KeyValueGeneratorMapping> mappings,
		bool isEF8Referenced
	)
	{
		foreach (var mapping in mappings)
		{
			if (mapping.InlineGeneratorClassName is null || mapping.InlineFactoryClassName is null)
				continue;

			ValueObjectEmitterHelpers.EmitEFValueGeneratorStrategy(
				body,
				mapping.ValueObjectTypeName,
				mapping.InlineGeneratorClassName,
				mapping.InlineFactoryClassName,
				TypeLibrary.EFSequentialGuidUuidV7Expression,
				ValueObjectEmitterHelpers.EFUuidV7StrategyDescription,
				isEF8Referenced,
				TypeDeclarationAccessibility.Internal
			);
			ValueObjectEmitterHelpers.EmitEFValueGeneratorStrategy(
				body,
				mapping.ValueObjectTypeName,
				mapping.InlineSqlServerGeneratorClassName!,
				mapping.InlineSqlServerFactoryClassName!,
				TypeLibrary.EFSequentialGuidSqlServerExpression,
				ValueObjectEmitterHelpers.EFSqlServerStrategyDescription,
				isEF8Referenced,
				TypeDeclarationAccessibility.Internal
			);
		}
	}

	/// <summary>Emits the identifier helper every generated key value generator hydrates from.</summary>
	static void EmitSequentialGuidClass(CodeWriter writer)
	{
		writer
			.XmlSummary(
				"Creates identifiers for value object keys in process, without a database round trip.",
				"The type is public so application code in any assembly can mint the identifier it wants a key to",
				"hold before SaveChanges; the generated key value generators produce the same values, so a key the",
				"application set is simply left alone.",
				"NewGuid produces an RFC 9562 version 7 identifier: a 48-bit big-endian Unix millisecond timestamp",
				"followed by random bytes. Values ascend by creation time in any store that compares the sixteen",
				"bytes in order - PostgreSQL, SQLite, MySQL, and non-clustered SQL Server keys.",
				"NewSqlServerGuid produces a value that ascends by creation time in SQL Server's uniqueidentifier",
				"ordering instead, which compares the trailing six bytes first. Use it for a clustered SQL Server",
				"key; the timestamp then occupies bytes 10 to 15 and the value is a version 4 UUID rather than a",
				"version 7 one.",
				"TryGetTimestamp and TryGetSqlServerTimestamp recover the creation time of a value produced by the",
				"matching method. MinSqlServerGuidFor and MaxSqlServerGuidFor produce inclusive bounds for that",
				"creation time so a key range comparison translates to an index seek."
			)
			.Class(
				new TypeDeclarationOptions(TypeLibrary.EFSequentialGuidClassName)
				{
					Accessibility = TypeDeclarationAccessibility.Public,
					IsStatic = true,
					IsPartial = false,
				},
				body =>
				{
					body.XmlSummary(
							"The largest Unix millisecond value a DateTimeOffset can represent, so a recovered",
							"timestamp cannot be out of range."
						)
						.Field(
							new FieldDeclarationOptions(
								"MaxUnixMilliseconds",
								LongType(),
								TypeDeclarationAccessibility.Private
							)
							{
								IsConst = true,
								Initializer = "253402300799999L",
							}
						);

					EmitUuidV7GuidMethods(body);
					EmitSqlServerGuidMethods(body);
					EmitTimestampMethods(body);
					EmitSqlServerBoundsMethods(body);
				}
			);
	}

	/// <summary>Emits the UUIDv7 creators, from the current time and from an explicit creation time.</summary>
	static void EmitUuidV7GuidMethods(CodeWriter body)
	{
		body.XmlSummary("Creates a new version 7 identifier.")
			.MethodExpression(
				new MethodDeclarationOptions("NewGuid", GuidType(), TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					ExpressionBody = "NewGuid(global::System.DateTimeOffset.UtcNow)",
				}
			)
			.XmlSummary("Creates a version 7 identifier for the given creation time.")
			.Method(
				new MethodDeclarationOptions("NewGuid", GuidType(), TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Parameters = [TimestampParameter()],
				},
				method =>
				{
					method.Assignment("var", "unixMilliseconds", "timestamp.ToUnixTimeMilliseconds()");
					EmitFillRandomBytes(method);
					EmitTimestampIntoBytes(method, 0);
					method.Assignment("bytes[6]", "(byte)((bytes[6] & 0x0F) | 0x70)");
					method.Assignment("bytes[8]", "(byte)((bytes[8] & 0x3F) | 0x80)");
					method.Return("new global::System.Guid(bytes, bigEndian: true)");
				}
			);
	}

	/// <summary>Emits the SQL Server-ordered creators, from the current time and from an explicit time.</summary>
	static void EmitSqlServerGuidMethods(CodeWriter body)
	{
		body.XmlSummary("Creates a new identifier that ascends in SQL Server's uniqueidentifier ordering.")
			.MethodExpression(
				new MethodDeclarationOptions("NewSqlServerGuid", GuidType(), TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					ExpressionBody = "NewSqlServerGuid(global::System.DateTimeOffset.UtcNow)",
				}
			)
			.XmlSummary(
				"Creates an identifier for the given creation time that ascends in SQL Server's",
				"uniqueidentifier ordering.",
				"SQL Server compares the trailing six bytes first, so the timestamp is written there and the",
				"remaining bytes stay random."
			)
			.Method(
				new MethodDeclarationOptions("NewSqlServerGuid", GuidType(), TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Parameters = [TimestampParameter()],
				},
				method =>
				{
					method.Assignment("var", "unixMilliseconds", "timestamp.ToUnixTimeMilliseconds()");
					EmitFillRandomBytes(method);
					EmitTimestampIntoBytes(method, 10);
					method.Assignment("bytes[6]", "(byte)((bytes[6] & 0x0F) | 0x40)");
					method.Assignment("bytes[8]", "(byte)((bytes[8] & 0x3F) | 0x80)");
					method.Return("new global::System.Guid(bytes, bigEndian: true)");
				}
			);
	}

	/// <summary>Emits the timestamp readers for both layouts.</summary>
	static void EmitTimestampMethods(CodeWriter body)
	{
		body.XmlSummary(
				"Reads the creation time of a value produced by NewGuid.",
				"Returns false for any other value, including an identifier created by a different generator or a",
				"timestamp outside the range a DateTimeOffset can represent."
			)
			.Method(
				new MethodDeclarationOptions("TryGetTimestamp", BooleanType(), TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Parameters = [GuidParameter("value"), TimestampOutParameter()],
				},
				method =>
				{
					EmitReadTimestampFromBytes(method, 0);
					method.IfBlock(
						"(bytes[6] & 0xF0) != 0x70",
						rejected =>
						{
							rejected.Assignment("timestamp", "default");
							rejected.Return("false");
						}
					);
					EmitAcceptTimestamp(method);
				}
			);

		body.XmlSummary(
				"Reads the creation time of a value produced by NewSqlServerGuid.",
				"Returns false for any other value, including an identifier created by a different generator or a",
				"timestamp outside the range a DateTimeOffset can represent."
			)
			.Method(
				new MethodDeclarationOptions(
					"TryGetSqlServerTimestamp",
					BooleanType(),
					TypeDeclarationAccessibility.Public
				)
				{
					IsStatic = true,
					Parameters = [GuidParameter("value"), TimestampOutParameter()],
				},
				method =>
				{
					EmitReadTimestampFromBytes(method, 10);
					EmitAcceptTimestamp(method);
				}
			);
	}

	/// <summary>Emits the byte reads shared by both timestamp readers.</summary>
	static void EmitReadTimestampFromBytes(CodeWriter method, int offset)
	{
		method.Assignment("global::System.Span<byte>", "bytes", "stackalloc byte[16]");
		method.MethodCallOn("value", "TryWriteBytes", "bytes", "bigEndian: true", "out _");
		var bytes = string.Join(
			" | ",
			Enumerable
				.Range(0, 5)
				.Select(index => $"((long)bytes[{index + offset}] << {40 - (index * 8)})")
				.Append($"bytes[{offset + 5}]")
		);
		method.Assignment("var", "unixMilliseconds", bytes);
	}

	/// <summary>Emits the range check and the timestamp a reader assigns once the value is known good.</summary>
	static void EmitAcceptTimestamp(CodeWriter method)
	{
		method.IfBlock(
			"unixMilliseconds < 0L || unixMilliseconds > MaxUnixMilliseconds",
			rejected =>
			{
				rejected.Assignment("timestamp", "default");
				rejected.Return("false");
			}
		);
		method.Assignment("timestamp", "global::System.DateTimeOffset.FromUnixTimeMilliseconds(unixMilliseconds)");
		method.Return("true");
	}

	/// <summary>Emits the inclusive range bounds for a SQL Server-ordered key at a given creation time.</summary>
	static void EmitSqlServerBoundsMethods(CodeWriter body)
	{
		var boundsNote = new[]
		{
			"Both bounds are inclusive, so a range query on the key is",
			"id &gt;= MinSqlServerGuidFor(t) &amp;&amp; id &lt;= MaxSqlServerGuidFor(t). The values exist only for",
			"comparison and are not valid version 7 identifiers.",
		};

		body.XmlSummary([
				"Creates the smallest identifier that exists at the given creation time in SQL Server's",
				"uniqueidentifier ordering.",
				.. boundsNote,
			])
			.MethodExpression(
				new MethodDeclarationOptions("MinSqlServerGuidFor", GuidType(), TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Parameters = [TimestampParameter()],
					ExpressionBody = "SqlServerGuidAt(timestamp, 0x00)",
				}
			)
			.XmlSummary([
				"Creates the largest identifier that exists at the given creation time in SQL Server's",
				"uniqueidentifier ordering.",
				.. boundsNote,
			])
			.MethodExpression(
				new MethodDeclarationOptions("MaxSqlServerGuidFor", GuidType(), TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Parameters = [TimestampParameter()],
					ExpressionBody = "SqlServerGuidAt(timestamp, 0xFF)",
				}
			)
			.Method(
				new MethodDeclarationOptions("SqlServerGuidAt", GuidType(), TypeDeclarationAccessibility.Private)
				{
					IsStatic = true,
					Parameters = [TimestampParameter(), new("filler", ByteType())],
				},
				method =>
				{
					method.Assignment("var", "unixMilliseconds", "timestamp.ToUnixTimeMilliseconds()");
					method.Assignment("global::System.Span<byte>", "bytes", "stackalloc byte[16]");
					method.MethodCallOn("bytes", "Fill", "filler");
					EmitTimestampIntoBytes(method, 10);
					method.Return("new global::System.Guid(bytes, bigEndian: true)");
				}
			);
	}

	/// <summary>Emits the random-byte fill both creators start from.</summary>
	static void EmitFillRandomBytes(CodeWriter method)
	{
		method.Assignment("global::System.Span<byte>", "bytes", "stackalloc byte[16]");
		method.MethodCallOn("global::System.Security.Cryptography.RandomNumberGenerator", "Fill", "bytes");
	}

	/// <summary>Emits the six big-endian timestamp bytes starting at <paramref name="offset"/>.</summary>
	static void EmitTimestampIntoBytes(CodeWriter method, int offset)
	{
		for (var index = 0; index < 5; index++)
			method.Assignment($"bytes[{index + offset}]", $"(byte)(unixMilliseconds >> {40 - (index * 8)})");

		method.Assignment($"bytes[{offset + 5}]", "(byte)unixMilliseconds");
	}

	static ParameterDeclarationOptions TimestampParameter() => new("timestamp", DateTimeOffsetType());

	static ParameterDeclarationOptions TimestampOutParameter() =>
		new("timestamp", DateTimeOffsetType()) { Modifier = ParameterModifier.Out };

	static ParameterDeclarationOptions GuidParameter(string name) => new(name, GuidType());

	static TypeReference GuidType() => new(new TypeIdentity("global::System.Guid", null));

	static TypeReference DateTimeOffsetType() => new(new TypeIdentity("global::System.DateTimeOffset", null));

	static TypeReference BooleanType() => new(new TypeIdentity("global::System.Boolean", null));

	static TypeReference ByteType() => new(new TypeIdentity("byte", null));

	static TypeReference LongType() => new(new TypeIdentity("long", null));

	/// <summary>
	/// Emits the convention that attaches a generated key value generator to every key property typed as an
	/// opted-in value object.
	/// </summary>
	static void EmitKeyValueGeneratorConventionClass(
		CodeWriter writer,
		ImmutableArray<KeyValueGeneratorMapping> mappings
	)
	{
		TypeReference conventionType = new(new TypeIdentity(TypeLibrary.EFModelFinalizingConventionFullTypeName, null));
		TypeReference modelBuilderType = new(new TypeIdentity(TypeLibrary.EFConventionModelBuilderFullTypeName, null));
		TypeReference contextType = new(
			new TypeIdentity(
				$"{TypeLibrary.EFConventionContextFullTypeName}<{TypeLibrary.EFConventionModelBuilderFullTypeName}>",
				null
			)
		);

		var factories = string.Join(
			", ",
			mappings.Select(mapping => $"[typeof({mapping.ValueObjectTypeName})] = typeof({mapping.FactoryTypeName})")
		);
		var sqlServerFactories = string.Join(
			", ",
			mappings.Select(mapping =>
				$"[typeof({mapping.ValueObjectTypeName})] = typeof({mapping.SqlServerFactoryTypeName})"
			)
		);
		TypeReference factoriesType = new(
			new TypeIdentity(
				"global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Type>",
				null
			)
		);

		writer
			.XmlSummary(
				"Attaches a generated key value generator to every key property typed as a value object that opted",
				$"in with GenerateEFValueGenerator. Register it with {TypeLibrary.EFValueObjectExtensionsClassName}",
				"UseValueObjectKeyGenerators() from ConfigureConventions.",
				$"The constructor selects the ordering: UUIDv7 by default, or SQL Server's uniqueidentifier ordering",
				"when constructed with that key ordering.",
				"A value supplied by domain code is never overwritten, and because this runs at the convention",
				"configuration source any entity configuration that already owns the key - ValueGeneratedNever(), an",
				"explicitly configured generator, or a store-generated default - wins.",
				"Only base Entity Framework Core APIs are used, so the convention holds for every provider."
			)
			.Class(
				new TypeDeclarationOptions(TypeLibrary.EFKeyValueGeneratorConventionClassName)
				{
					Accessibility = TypeDeclarationAccessibility.Public,
					IsSealed = true,
					IsPartial = false,
					BaseType = conventionType,
				},
				body =>
				{
					body.Field(
						new FieldDeclarationOptions("Factories", factoriesType, TypeDeclarationAccessibility.Private)
						{
							IsStatic = true,
							IsReadOnly = true,
							Initializer =
								$"new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Type> {{ {factories} }}",
						}
					);

					body.Field(
						new FieldDeclarationOptions(
							"SqlServerFactories",
							factoriesType,
							TypeDeclarationAccessibility.Private
						)
						{
							IsStatic = true,
							IsReadOnly = true,
							Initializer =
								$"new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Type> {{ {sqlServerFactories} }}",
						}
					);

					body.Field(
						new FieldDeclarationOptions("_factories", factoriesType, TypeDeclarationAccessibility.Private)
						{
							IsReadOnly = true,
						}
					);

					body.XmlSummary("Creates the convention using the default UUIDv7 ordering.")
						.Constructor(
							new ConstructorDeclarationOptions(
								TypeLibrary.EFKeyValueGeneratorConventionClassName,
								TypeDeclarationAccessibility.Public
							)
							{
								Initializer = $"this({TypeLibrary.EFKeyOrderingEnumFullTypeName}.UuidV7)",
							},
							_ => { }
						);

					body.XmlSummary(
							"Creates the convention using the given key ordering.",
							"The ordering is fixed for the lifetime of the convention, and conventions are created once per",
							"model, so it never changes between two runs over the same model."
						)
						.Constructor(
							new ConstructorDeclarationOptions(
								TypeLibrary.EFKeyValueGeneratorConventionClassName,
								TypeDeclarationAccessibility.Public
							)
							{
								Parameters =
								[
									new(
										"ordering",
										new TypeReference(
											new TypeIdentity(TypeLibrary.EFKeyOrderingEnumFullTypeName, null)
										)
									),
								],
							},
							ctor =>
								ctor.Assignment(
									"_factories",
									$"ordering == {TypeLibrary.EFKeyOrderingEnumFullTypeName}.SqlServer ? SqlServerFactories : Factories"
								)
						);

					body.Method(
						new MethodDeclarationOptions("ProcessModelFinalizing", TypeDeclarationAccessibility.Public)
						{
							// An interface implementation, not an override: the generated class declares
							// IModelFinalizingConvention as its base list.
							Parameters = [new("modelBuilder", modelBuilderType), new("context", contextType)],
						},
						method =>
							method.Block(
								"foreach (var entityType in modelBuilder.Metadata.GetEntityTypes())",
								entityLoop =>
									entityLoop.Block(
										"foreach (var property in entityType.GetDeclaredProperties())",
										propertyLoop =>
											propertyLoop.IfBlock(
												"property.IsKey() && !property.IsForeignKey() && (property.GetValueGeneratedConfigurationSource() is null or global::Microsoft.EntityFrameworkCore.Metadata.ConfigurationSource.Convention) && (property.GetValueGeneratorFactoryConfigurationSource() is null or global::Microsoft.EntityFrameworkCore.Metadata.ConfigurationSource.Convention) && _factories.TryGetValue(property.ClrType, out var factoryType)",
												ifBody =>
												{
													ifBody.MethodCallOn(
														"property.Builder",
														"ValueGenerated",
														$"{TypeLibrary.EFValueGeneratedFullTypeName}.OnAdd"
													);
													ifBody.MethodCallOn(
														"property.Builder",
														"HasValueGeneratorFactory",
														"factoryType"
													);
												}
											)
									)
							)
					);
				}
			);
	}

	/// <summary>
	/// Describes one generated key value generator: the value object it generates an identifier for, the
	/// factory Entity Framework Core instantiates for each ordering strategy, and - when the declaring
	/// assembly does not reference Entity Framework Core - the inline generator pairs emitted into the
	/// registry.
	/// </summary>
	readonly record struct KeyValueGeneratorMapping(
		string ValueObjectTypeName,
		string FactoryTypeName,
		string SqlServerFactoryTypeName,
		string? InlineGeneratorClassName,
		string? InlineFactoryClassName,
		string? InlineSqlServerGeneratorClassName,
		string? InlineSqlServerFactoryClassName
	);

	static string SanitizeIdentifier(string typeName)
	{
		var name = typeName.StartsWith("global::", StringComparison.Ordinal)
			? typeName.Substring("global::".Length)
			: typeName;
		System.Text.StringBuilder builder = new(name.Length);
		foreach (var character in name)
			builder.Append(char.IsLetterOrDigit(character) ? character : '_');

		return builder.ToString();
	}

	static string UniqueName(string name, HashSet<string> usedNames)
	{
		var candidate = name;
		var suffix = 2;
		while (!usedNames.Add(candidate))
			candidate = $"{name}_{suffix++}";

		return candidate;
	}

	static void EmitInlineConverterFields(CodeWriter body, ImmutableArray<InlineConverterDefinition> definitions)
	{
		var valueConverterType =
			TypeLibrary.Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter.AsTypeReference();

		foreach (var definition in definitions)
		{
			body.Field(
				new FieldDeclarationOptions(
					definition.FieldName,
					valueConverterType,
					TypeDeclarationAccessibility.Private
				)
				{
					IsStatic = true,
					IsReadOnly = true,
					Initializer = $"new {definition.ClassName}()",
				}
			);
		}
	}

	static void EmitInlineConverters(
		CodeWriter body,
		ImmutableArray<InlineConverterDefinition> definitions,
		bool isEF8Referenced
	)
	{
		foreach (var definition in definitions)
		{
			ValueObjectEFConverterEmitter.EmitConverterClass(
				body,
				new EFConverterDefinition(
					definition.ClassName,
					TypeDeclarationAccessibility.Internal,
					definition.BaseTypeName,
					definition.ValueObjectTypeName,
					definition.ProviderTypeName,
					definition.ToProviderExpression,
					definition.FromProviderExpression,
					ValueObjectEmitterHelpers.EFJsonReaderWriterType(definition.ProviderTypeName),
					isEF8Referenced
				)
			);
		}
	}
}

/// <summary>
/// Describes an inline converter emitted into the assembly-level registry, including the shared static field
/// that holds its instance.
/// </summary>
readonly record struct InlineConverterDefinition(
	string ClassName,
	string FieldName,
	string BaseTypeName,
	string ValueObjectTypeName,
	string ProviderTypeName,
	string ToProviderExpression,
	string FromProviderExpression
);
