namespace Purview.ValueObjects.SourceGenerator.ValueObject;

/// <summary>
/// Emits the assembly-level <see cref="TypeLibrary.ScalarRuleAdapterName"/> composition type into consumer
/// compilations that reference both <c>Purview.ValueObjects</c> and <c>Purview.ZodSharp</c>.
/// </summary>
/// <remarks>
/// <para>
/// The adapter turns a rule written against a scalar's underlying value (<c>IValidationRule&lt;TValue&gt;</c>)
/// into a rule that validates the value object as a unit (<c>IValidationRule&lt;TSelf&gt;</c>), so a
/// <c>[ZodRule]</c>-mapped attribute can apply it to the value object itself. It only needs public runtime
/// contracts, so this generator can emit it: it reads no other generator's output.
/// </para>
/// <para>
/// The type is <see cref="TypeDeclarationAccessibility.Internal"/> and emitted once per compilation, so a
/// consumer that references two assemblies which both emit it never sees the name twice. ZodSharp's generator
/// references it by fully qualified text, because a generator cannot resolve another generator's symbols.
/// </para>
/// </remarks>
static class ZodSharpScalarRuleAdapterEmitter
{
	/// <summary>Describes whether the adapter can be, or needs to be, emitted for a compilation.</summary>
	/// <param name="IsZodSharpReferenced">True when the compilation references the Purview.ZodSharp runtime.</param>
	/// <param name="AdapterAlreadyDeclared">True when the compilation declares the adapter in its own source.</param>
	public readonly record struct EmissionState(bool IsZodSharpReferenced, bool AdapterAlreadyDeclared)
	{
		/// <summary>True when the adapter source should be added to the compilation.</summary>
		public bool ShouldEmit => IsZodSharpReferenced && !AdapterAlreadyDeclared;
	}

	/// <summary>
	/// Resolves whether the compilation wants the adapter: it is only emitted when the ZodSharp runtime is
	/// referenced (the adapter forwards to its rule contract) and the consumer has not declared the type
	/// itself, which keeps the copied adapters the earlier guidance produced working.
	/// </summary>
	/// <param name="compilation">The compilation being generated for.</param>
	/// <remarks>
	/// Only a declaration in this compilation counts. A referenced assembly that also emitted its own adapter
	/// declares it <see langword="internal"/>, so it is invisible to this compilation's name lookup and must
	/// not suppress the local copy.
	/// </remarks>
	public static EmissionState ResolveState(Compilation compilation) =>
		new(
			IsZodSharpReferenced: ValueObjectSymbolInspector.IsZodSharpReferenced(compilation),
			AdapterAlreadyDeclared: IsDeclaredInSource(compilation)
		);

	static bool IsDeclaredInSource(Compilation compilation) =>
		compilation.GetTypeByMetadataName(TypeLibrary.ScalarRuleAdapterMetadataName)
			is { DeclaringSyntaxReferences.Length: > 0 };

	/// <summary>Emits the adapter.</summary>
	public static void Emit(CodeWriter writer)
	{
		// The adapter is a composition type with no error identity of its own; the inner rule (or the applied
		// attribute) supplies it, so the ZodSharp convention check is silenced for this file only.
		writer.AutoGeneratedHeader(pragmas: ["ZODSGEN042"]);
		writer.FileScopedNamespace(TypeLibrary.ValueObjectsNamespace);

		writer
			.XmlSummary(
				"Turns a rule written against a scalar value object's underlying value into a rule that validates",
				"the value object as a unit, so a [ZodRule]-mapped attribute can apply it to the value object",
				"itself. Emitted when this project references both Purview.ValueObjects and Purview.ZodSharp."
			)
			.RecordStruct(
				new TypeDeclarationOptions(TypeLibrary.ScalarRuleAdapterName)
				{
					Accessibility = TypeDeclarationAccessibility.Internal,
					IsPartial = false,
					IsReadOnly = true,
					GenericTypes =
					[
						new GenericTypeParameterOptions(SelfName)
						{
							Constraints =
							[
								TypeLibrary
									.Purview.ValueObjects.IScalarValueObject.MakeGeneric(SelfReference, ValueReference)
									.RenderFullName,
							],
						},
						new GenericTypeParameterOptions(ValueName),
						new GenericTypeParameterOptions(RuleName)
						{
							Constraints =
							[
								TypeLibrary.ZodSharp.Core.IValidationRule.MakeGeneric(ValueReference).RenderFullName,
							],
						},
					],
					PrimaryConstructorParameters = [new("Rule", RuleTypeReference)],
					Interfaces = [RuleInterfaceForSelf],
				},
				body =>
				{
					body.XmlSummary("True when the adapted rule accepts the value object's underlying value.")
						.MethodExpression(
							new MethodDeclarationOptions(
								"IsValid",
								PurviewTypeLibrary.System.Boolean,
								TypeDeclarationAccessibility.Public
							)
							{
								Parameters = [new("value", SelfReference, ParameterModifier.In)],
								ExpressionBody = "Rule.IsValid(value.Value)",
							}
						);

					body.XmlSummary("The adapted rule's message for the value object's underlying value.")
						.MethodExpression(
							new MethodDeclarationOptions(
								"GetErrorMessage",
								PurviewTypeLibrary.System.String,
								TypeDeclarationAccessibility.Public
							)
							{
								Parameters = [new("value", SelfReference, ParameterModifier.In)],
								ExpressionBody = "Rule.GetErrorMessage(value.Value)",
							}
						);
				}
			);
	}

	const string SelfName = "TSelf";

	const string ValueName = "TValue";

	const string RuleName = "TRule";

	/// <summary>
	/// The type parameters are emitted as named identities without a namespace, which renders them as bare
	/// parameter names: a <c>TypeReference</c> created for an open generic parameter cannot be used in
	/// a declaration, which validates that every parameter names a type.
	/// </summary>
	static TypeReference SelfReference => new(new TypeIdentity(SelfName, null));

	static TypeReference ValueReference => new(new TypeIdentity(ValueName, null));

	static TypeReference RuleTypeReference => new(new TypeIdentity(RuleName, null));

	static TypeReference RuleInterfaceForSelf =>
		new(TypeLibrary.ZodSharp.Core.IValidationRule.MakeGeneric(SelfReference));
}
