namespace Purview.ValueObjects.Serialization;

/// <summary>
/// Specifies assembly-level defaults for value object code generation.
/// These defaults apply to every <c>[Scalar]</c>/<c>[ValueObject]</c> type in the assembly and can be
/// overridden on individual <see cref="ScalarAttribute"/> / <see cref="ValueObjectAttribute"/> attributes.
/// </summary>
[AttributeUsage(AttributeTargets.Assembly)]
public sealed class ValueObjectDefaultsAttribute : Attribute
{
	/// <summary>
	/// Gets or sets whether a JSON converter should be generated by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateJsonConverter { get; init; } = true;

	/// <summary>
	/// Gets or sets whether <see cref="IComparable{T}"/> support should be generated by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateComparable { get; init; } = true;

	/// <summary>
	/// Gets or sets whether comparison operators should be generated by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateComparisonOperators { get; init; } = true;

	/// <summary>
	/// Gets or sets whether enum properties should be generated from the underlying value by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateEnumProperties { get; init; } = true;

	/// <summary>
	/// Gets or sets whether an implicit conversion from the primitive value should be generated by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateImplicitFromPrimitive { get; init; } = true;

	/// <summary>
	/// Gets or sets whether an implicit conversion to the primitive value should be generated by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateImplicitToPrimitive { get; init; } = true;

	/// <summary>
	/// Gets or sets whether a static <c>Empty</c> instance should be generated by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateEmpty { get; init; } = true;

	/// <summary>
	/// Gets or sets whether parameterless constructors should be generated by default for
	/// <c>[ValueObject]</c> types. When true, generates a private parameterless constructor for EF Core
	/// compatibility.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateConstructor { get; init; } = true;

	/// <summary>
	/// Gets or sets how <c>[ValueObject]</c> types are mapped when the Entity Framework Core integration
	/// is active by default.
	/// </summary>
	/// <value>Defaults to <see cref="EfMapping.ComplexType"/>.</value>
	/// <remarks>
	/// Entity Framework members are emitted only when the consuming project references
	/// <c>Microsoft.EntityFrameworkCore</c>; otherwise this option is ignored. Set to
	/// <see cref="EfMapping.None"/> to opt out the whole assembly.
	/// </remarks>
	public EfMapping EfMapping { get; init; } = EfMapping.ComplexType;

	/// <summary>
	/// Gets or sets whether an Entity Framework Core <c>ValueConverter</c> should be generated by default
	/// for <c>[Scalar]</c> types.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	/// <remarks>
	/// Entity Framework members are emitted only when the consuming project references
	/// <c>Microsoft.EntityFrameworkCore</c>; otherwise this option is ignored.
	/// </remarks>
	public bool GenerateEfConverter { get; init; } = true;

	/// <summary>
	/// Gets or sets whether an Entity Framework Core <c>ValueComparer</c> should be generated by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	/// <remarks>
	/// Entity Framework members are emitted only when the consuming project references
	/// <c>Microsoft.EntityFrameworkCore</c>; otherwise this option is ignored.
	/// </remarks>
	public bool GenerateEfComparer { get; init; } = true;

	/// <summary>
	/// Gets or sets the deserialization mode used by generated JSON converters by default.
	/// </summary>
	/// <value>Defaults to <see cref="ValueObjectDeserializationMode.Hydrate"/>.</value>
	public ValueObjectDeserializationMode DeserializationMode { get; init; } = ValueObjectDeserializationMode.Hydrate;

	/// <summary>
	/// Gets or sets how a source-generated ZodSharp schema validator (from the <c>[ZodSchema]</c>
	/// attribute) participates in the generated <c>Create</c> path by default.
	/// </summary>
	/// <value>Defaults to <see cref="ZodSchemaMode.InAdditionToHooks"/>.</value>
	public ZodSchemaMode ZodSchemaMode { get; init; } = ZodSchemaMode.InAdditionToHooks;

	/// <summary>
	/// Initializes a new instance of the <see cref="ValueObjectDefaultsAttribute"/> class with default settings.
	/// </summary>
	public ValueObjectDefaultsAttribute() { }
}
