namespace Purview.ValueObjects.Serialization;

/// <summary>
/// Specifies assembly-level defaults for value object code generation.
/// These defaults apply to every <c>[Scalar]</c>/<c>[ValueObject]</c> type in the assembly and can be
/// overridden on individual <see cref="ScalarAttribute"/> / <see cref="ValueObjectAttribute"/> attributes.
/// </summary>
[AttributeUsage(AttributeTargets.Assembly)]
public sealed class ValueObjectDefaultsAttribute : Attribute
{
	/// <summary>
	/// Gets or sets whether a JSON converter should be generated by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateJsonConverter { get; init; } = true;

	/// <summary>
	/// Gets or sets whether comparison against the underlying value and the comparison operators should be
	/// generated by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	/// <remarks>
	/// The value object always implements <see cref="IComparable{T}"/> of itself and
	/// <see cref="IComparable"/> (and a scalar always exposes <c>CompareTo(TValue)</c>), because the
	/// value-object contract requires them. Setting this to <see langword="false"/> drops the extra
	/// <c>IComparable&lt;TValue&gt;</c> interface and the comparison operators.
	/// </remarks>
	public bool GenerateComparable { get; init; } = true;

	/// <summary>
	/// Gets or sets whether comparison operators should be generated by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateComparisonOperators { get; init; } = true;

	/// <summary>
	/// Gets or sets whether enum properties should be generated from the underlying value by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateEnumProperties { get; init; } = true;

	/// <summary>
	/// Gets or sets whether an implicit conversion from the primitive value should be generated by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateImplicitFromPrimitive { get; init; } = true;

	/// <summary>
	/// Gets or sets whether an implicit conversion to the primitive value should be generated by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateImplicitToPrimitive { get; init; } = true;

	/// <summary>
	/// Gets or sets whether a static <c>Empty</c> instance should be generated by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateEmpty { get; init; } = true;

	/// <summary>
	/// Gets or sets whether parameterless constructors should be generated by default for
	/// <c>[ValueObject]</c> types. When true, generates a private parameterless constructor for EF Core
	/// compatibility.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	public bool GenerateConstructor { get; init; } = true;

	/// <summary>
	/// Gets or sets how <c>[ValueObject]</c> types are mapped when the Entity Framework Core integration
	/// is active by default.
	/// </summary>
	/// <value>Defaults to <see cref="EntityFrameworkMapping.ComplexType"/>.</value>
	/// <remarks>
	/// Entity Framework members are emitted only when the consuming project references
	/// <c>Microsoft.EntityFrameworkCore</c>; otherwise this option is ignored. Set to
	/// <see cref="EntityFrameworkMapping.None"/> to opt out the whole assembly.
	/// </remarks>
	public EntityFrameworkMapping EFMapping { get; init; } = EntityFrameworkMapping.ComplexType;

	/// <summary>
	/// Gets or sets whether an Entity Framework Core <c>ValueConverter</c> should be generated by default
	/// for <c>[Scalar]</c> types.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	/// <remarks>
	/// Entity Framework members are emitted only when the consuming project references
	/// <c>Microsoft.EntityFrameworkCore</c>; otherwise this option is ignored.
	/// </remarks>
	public bool GenerateEFConverter { get; init; } = true;

	/// <summary>
	/// Gets or sets whether an Entity Framework Core <c>ValueComparer</c> should be generated by default.
	/// </summary>
	/// <value>Defaults to <see langword="true"/>.</value>
	/// <remarks>
	/// Entity Framework members are emitted only when the consuming project references
	/// <c>Microsoft.EntityFrameworkCore</c>; otherwise this option is ignored.
	/// </remarks>
	public bool GenerateEFComparer { get; init; } = true;

	/// <summary>
	/// Gets or sets whether an Entity Framework Core value generator should be generated by default
	/// for Guid-backed <c>[Scalar]</c> types.
	/// </summary>
	/// <value>Defaults to <see langword="false"/>.</value>
	/// <remarks>
	/// Entity Framework members are emitted only when the consuming project references
	/// <c>Microsoft.EntityFrameworkCore</c>; otherwise this option is ignored. Value generation is
	/// supported for Guid-backed scalars only.
	/// </remarks>
	public bool GenerateEFValueGenerator { get; init; }

	/// <summary>
	/// Gets or sets the default string normalization applied to every string-backed scalar and every
	/// string member of a <c>[ValueObject]</c> in the assembly.
	/// </summary>
	/// <value>Defaults to <see langword="false"/>.</value>
	/// <remarks>
	/// A <c>[Scalar]</c>/<c>[Scalar&lt;T&gt;]</c> type can override this with
	/// <see cref="ScalarOptionsAttribute.Trim"/>, and a complex member can override it with
	/// <see cref="StringNormalizeAttribute"/>. The default is applied silently to string targets only;
	/// it is ignored where the value object implements its own <c>OnNormalize</c> hook or declares its own
	/// <c>Create</c>.
	/// </remarks>
	public bool Trim { get; init; }

	/// <summary>
	/// Gets or sets the default casing canonicalization applied to every string-backed scalar and every
	/// string member of a <c>[ValueObject]</c> in the assembly.
	/// </summary>
	/// <value>Defaults to <see cref="StringCasing.None"/>.</value>
	/// <remarks>
	/// A <c>[Scalar]</c>/<c>[Scalar&lt;T&gt;]</c> type can override this with
	/// <see cref="ScalarOptionsAttribute.Casing"/>, and a complex member can override it with
	/// <see cref="StringNormalizeAttribute"/>. The default is applied silently to string targets only;
	/// it is ignored where the value object implements its own <c>OnNormalize</c> hook or declares its own
	/// <c>Create</c>.
	/// </remarks>
	public StringCasing Casing { get; init; } = StringCasing.None;

	/// <summary>
	/// Gets or sets the deserialization mode used by generated JSON converters by default.
	/// </summary>
	/// <value>Defaults to <see cref="ValueObjectDeserializationMode.Hydrate"/>.</value>
	public ValueObjectDeserializationMode DeserializationMode { get; init; } = ValueObjectDeserializationMode.Hydrate;

	/// <summary>
	/// Gets or sets how a source-generated ZodSharp schema validator (from the <c>[ZodSchema]</c>
	/// attribute) participates in the generated <c>Create</c> path by default.
	/// </summary>
	/// <value>Defaults to <see cref="ZodSchemaMode.InAdditionToHooks"/>.</value>
	public ZodSchemaMode ZodSchemaMode { get; init; } = ZodSchemaMode.InAdditionToHooks;

	/// <summary>
	/// Initializes a new instance of the <see cref="ValueObjectDefaultsAttribute"/> class with default settings.
	/// </summary>
	public ValueObjectDefaultsAttribute() { }
}
