using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Purview.ValueObjects.EFDomainSample.Domain;

try
{
	await using SqliteConnection connection = new("Data Source=:memory:");
	await connection.OpenAsync();

	await using SampleDbContext context = new(
		new DbContextOptionsBuilder<SampleDbContext>().UseSqlite(connection).Options
	);
	await context.Database.EnsureCreatedAsync();

	var systemTenant = TenantId.Hydrate(Guid.NewGuid());
	var otherTenant = TenantId.Hydrate(Guid.NewGuid());
	context.CurrentTenantId = systemTenant;

	Console.WriteLine("== Domain entity with typed identifiers ==");
	var customer = Customer.Create(
		CustomerId.Hydrate(Guid.Empty),
		systemTenant,
		EmailAddress.Create("  Owner@Example.COM  "),
		"  Contoso  "
	);
	Console.WriteLine($"Customer.Create -> {customer.Name} <{customer.Email.Value}>");

	Console.WriteLine();
	Console.WriteLine("== Keys generated by the value object ==");

	// The record is built from the entity; the identifier is still the CLR default, so the generated key
	// value generator (a version 7 UUID) supplies it on save. Adding the graph lets Entity Framework Core
	// order the inserts: the tenant is the principal and is written first.
	TenantRecord tenantRecord = new()
	{
		Id = systemTenant,
		Key = TenantKey.Create("  CONTOSO "),
		DisplayName = "Contoso",
	};
	CustomerRecord customerRecord = new()
	{
		Id = customer.Id,
		TenantId = customer.TenantId,
		Email = customer.Email,
		Name = customer.Name,
		Tenant = tenantRecord,
	};
	context.Customers.Add(customerRecord);

	await context.SaveChangesAsync();
	Console.WriteLine($"Generated customer id -> {customerRecord.Id.Value} (v{customerRecord.Id.Value.Version})");
	Console.WriteLine($"Tenant key -> '{tenantRecord.Key.Value}'");

	Console.WriteLine();
	Console.WriteLine("== Identifiers the application owns are not overwritten ==");

	// ValueObjectSequentialGuid is generated as a public type, so application code can mint the identifier an
	// entity is saved with - and read its creation time back - instead of leaving the key unset. The generated
	// generator only fills a CLR default, so the minted value is persisted as-is.
	var mintedId = CustomerId.Create(ValueObjectSequentialGuid.NewGuid());
	context.Customers.Add(
		new CustomerRecord
		{
			Id = mintedId,
			TenantId = systemTenant,
			Email = customer.Email,
			Name = "Second customer",
		}
	);
	await context.SaveChangesAsync();
	Console.WriteLine($"Application-minted id -> {mintedId.Value} (v{mintedId.Value.Version})");
	Console.WriteLine(
		$"Minted at -> {(ValueObjectSequentialGuid.TryGetTimestamp(mintedId.Value, out var mintedAt) ? mintedAt : default):O}"
	);

	// The same helper offers the SQL Server ordering strategy for a clustered SQL Server key.
	Console.WriteLine($"SQL Server ordering variant -> {ValueObjectSequentialGuid.NewSqlServerGuid()}");

	Console.WriteLine();
	Console.WriteLine("== Query filter over value object properties ==");
	CustomerRecord otherTenantCustomer = new()
	{
		Id = CustomerId.Hydrate(Guid.Empty),
		TenantId = otherTenant,
		Email = EmailAddress.Create("other@example.com"),
		Name = "Other tenant",
		Tenant = new TenantRecord
		{
			Id = otherTenant,
			Key = TenantKey.Create("other"),
			DisplayName = "Other tenant",
		},
	};
	context.Customers.Add(otherTenantCustomer);
	await context.SaveChangesAsync();

	var visibleFromSystemTenant = await context.Customers.CountAsync();
	context.CurrentTenantId = otherTenant;
	var visibleFromOtherTenant = await context.Customers.CountAsync();
	Console.WriteLine($"Customers visible to the system tenant -> {visibleFromSystemTenant}");
	Console.WriteLine($"Customers visible to the other tenant -> {visibleFromOtherTenant}");

	Console.WriteLine();
	Console.WriteLine("== Queries compare value objects directly ==");
	context.CurrentTenantId = systemTenant;
	var found = await context.Customers.SingleAsync(record => record.Id == customerRecord.Id);
	Console.WriteLine($"Round-trip -> {found.Name} <{found.Email.Value}>");

	return 0;
}
catch (DbUpdateException exception)
{
	await Console.Error.WriteLineAsync(exception.InnerException?.Message ?? exception.Message);
	return 1;
}
